CoolBoard API: Irene3000 Class Reference
Irene3000 Class Reference
This class is provided to manage the Irene3000 Ph/Temperature Shield.
#include <Irene3000.h>
Classes
struct parameters_T
struct state
Public Member Functions
void begin ()
bool config ()
void printConf ()
String read ()
int readButton ()
void setGain (adsGain_t gain)
int readADSChannel2 (adsGain_t gain)
float readPh (double t)
double readTemp ()
void resetParams ()
void calibratepH7 ()
void calibratepH4 ()
void calcpHSlope ()
adsGain_t gainConvert (uint16_t tempGain)
bool saveParams ()
Private Attributes
Adafruit_ADS1115 ads
struct Irene3000::parameters_T params
struct Irene3000::state waterTemp
struct Irene3000::state phProbe
struct Irene3000::state adc2
const float vRef = 1.024
const float opampGain = 5.25
Detailed Description
This class is provided to manage the Irene3000 Ph/Temperature Shield.
Definition at line 59 of file Irene3000.h.
Class Documentation
Irene3000::parameters_T
struct Irene3000::parameters_T
PH Sensor Calibration parameters
pH7Cal : PH 7 Calibration value
pH4Cal : PH 4 Calibration value
pHStep : PH Slope Step value
Definition at line 111 of file Irene3000.h.
Class Members
unsigned int WriteCheck
int pH7Cal
int pH4Cal
float pHStep
Irene3000::state
struct Irene3000::state
Irene sensors state struct
active : if the related sensor is active or not
gain : what is the used gain for the related sensor (used only for the free channel)
type : the type of the used sensor(used only for the free channel)
Definition at line 128 of file Irene3000.h.
Class Members
bool active
adsGain_t gain
String type
Member Function Documentation
begin()
void Irene3000::begin (void)
Irene3000::begin(): This method is provided to start the Irene3000
Definition at line 52 of file Irene3000.cpp.
References ads, Adafruit_ADS1015::begin(), calibratepH4(), calibratepH7(), readButton(), and saveParams().
Referenced by CoolBoard::begin().
config()
bool Irene3000::config ()
Irene3000::config(): This method is provided to configure the Irene3000 shield through a configuration file
Returns
true if successful,false otherwise
Definition at line 203 of file Irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, gainConvert(), params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, phProbe, Irene3000::parameters_T::pHStep, Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::begin().
printConf()
void Irene3000::printConf ()
Irene3000::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 391 of file Irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, phProbe, Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::begin().
read()
String Irene3000::read (void)
Irene3000:read(): This method is provided to read the Irene3000 sensors data
Returns
json string of the sensors data
Definition at line 133 of file Irene3000.cpp.
References Irene3000::state::active, adc2, Irene3000::state::gain, phProbe, readADSChannel2(), readPh(), readTemp(), Irene3000::state::type, and waterTemp.
Referenced by CoolBoard::readSensors().
readButton()
int Irene3000::readButton ()
Irene3000::readButton(): This method is provided to read the Irene3000 button
Returns
the button value
Definition at line 434 of file Irene3000.cpp.
References ads, button, GAIN_TWOTHIRDS, Adafruit_ADS1015::readADC_SingleEnded(), and setGain().
Referenced by begin().
setGain()
void Irene3000::setGain (adsGain_t gain)
Irene3000::setGain(gain): This method is provided to set the ADS chip gain
Definition at line 462 of file Irene3000.cpp.
References ads, and Adafruit_ADS1015::setGain().
Referenced by calibratepH4(), calibratepH7(), readADSChannel2(), readButton(), readPh(), and readTemp().
readADSChannel2()
int Irene3000::readADSChannel2 (adsGain_t gain)
Irene3000::readADSChannel2(gain): This method is provided to read from the ADS channel 2 . ADS Channel 2 is free and the user can connect another analog sensor to it.
Returns
the ADS Channel 2 value
Definition at line 484 of file Irene3000.cpp.
References ads, freeAdc, Adafruit_ADS1015::readADC_SingleEnded(), and setGain().
Referenced by read().
readPh()
float Irene3000::readPh (double t)
Irene3000::readPh(double t): This method is provided to read the PH probe note that for the best results, PH must be correlated to Temperature.
Returns
the PH probe value
Definition at line 515 of file Irene3000.cpp.
References ADC_MAXIMUM_VALUE, ads, GAIN_FOUR, opampGain, params, ph, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, Adafruit_ADS1015::readADC_SingleEnded(), REFERENCE_VOLTAGE_GAIN_4, setGain(), and vRef.
Referenced by read().
readTemp()
double Irene3000::readTemp ()
Irene3000::readTemp(gain): This method is provided to read the Temeperature probe
Returns
the Temperature probe value
Definition at line 561 of file Irene3000.cpp.
References ads, GAIN_EIGHT, Adafruit_ADS1015::readADC_SingleEnded(), setGain(), temp, and V_GAIN_8.
Referenced by read().
resetParams()
void Irene3000::resetParams (void)
Irene3000::resetParams(): This method is provided to reset the PH configuration, assuming Ideal configuration
Definition at line 706 of file Irene3000.cpp.
References params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, Write_Check, and Irene3000::parameters_T::WriteCheck.
calibratepH7()
void Irene3000::calibratepH7 ()
Irene3000::calibratepH7(): This method is provided to calibrate the PH probe to 7
Definition at line 632 of file Irene3000.cpp.
References ads, calcpHSlope(), GAIN_FOUR, params, ph, Irene3000::parameters_T::pH7Cal, Adafruit_ADS1015::readADC_SingleEnded(), and setGain().
Referenced by begin(), and CoolBoard::update().
calibratepH4()
void Irene3000::calibratepH4 ()
Irene3000::calibratepH4(): This method is provided to calibrate the PH probe to 4
Definition at line 659 of file Irene3000.cpp.
References ads, calcpHSlope(), GAIN_FOUR, params, ph, Irene3000::parameters_T::pH4Cal, Adafruit_ADS1015::readADC_SingleEnded(), and setGain().
Referenced by begin(), and CoolBoard::update().
calcpHSlope()
void Irene3000::calcpHSlope ()
Irene3000::calcpHSlop(): This method is provided to calculate th PH slope
Definition at line 685 of file Irene3000.cpp.
References opampGain, params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, Irene3000::parameters_T::pHStep, and vRef.
Referenced by calibratepH4(), and calibratepH7().
gainConvert()
adsGain_t Irene3000::gainConvert (uint16_t tempGain)
Irene3000::gainConvert(gain : { 0.67 ,1,2,4,8,16 }) This method is provided to convert the gain to Internal Constants
Returns
internal representation of the ADS gain
Definition at line 732 of file Irene3000.cpp.
References GAIN_EIGHT, GAIN_FOUR, GAIN_ONE, GAIN_SIXTEEN, GAIN_TWO, and GAIN_TWOTHIRDS.
Referenced by config().
saveParams()
bool Irene3000::saveParams ()
Definition at line 757 of file Irene3000.cpp.
References params, Irene3000::parameters_T::pH4Cal, Irene3000::parameters_T::pH7Cal, and Irene3000::parameters_T::pHStep.
Referenced by begin(), and CoolBoard::update().
Member Data Documentation
ads
Adafruit_ADS1115 Irene3000::ads private
ADS1115 instance
Definition at line 99 of file Irene3000.h.
Referenced by begin(), calibratepH4(), calibratepH7(), readADSChannel2(), readButton(), readPh(), readTemp(), and setGain().
params
struct Irene3000::parameters_T Irene3000::params private
Referenced by calcpHSlope(), calibratepH4(), calibratepH7(), config(), readPh(), resetParams(), and saveParams().
waterTemp
struct Irene3000::state Irene3000::waterTemp private
Referenced by config(), printConf(), and read().
phProbe
struct Irene3000::state Irene3000::phProbe private
Referenced by config(), printConf(), and read().
adc2
struct Irene3000::state Irene3000::adc2 private
Referenced by config(), printConf(), and read().
vRef
const float Irene3000::vRef = 1.024 private
vRef constant used for ADC conversion
Definition at line 139 of file Irene3000.h.
Referenced by calcpHSlope(), and readPh().
opampGain
const float Irene3000::opampGain = 5.25 private
opAmpGain constant used for ADC conversion
Definition at line 144 of file Irene3000.h.
Referenced by calcpHSlope(), and readPh().
The documentation for this class was generated from the following files:
Irene3000.h
Irene3000.cpp