CoolBoard API: BME280 Class Reference
BME280 Class Reference
#include <CoolSparkFunBME280.h>
Public Member Functions
BME280 (void)
uint8_t begin (void)
void reset (void)
float readFloatPressure (void)
float readFloatAltitudeMeters (void)
float readFloatAltitudeFeet (void)
float readFloatHumidity (void)
float readTempC (void)
float readTempF (void)
void readRegisterRegion (uint8_t *, uint8_t, uint8_t)
uint8_t readRegister (uint8_t)
int16_t readRegisterInt16 (uint8_t offset)
void writeRegister (uint8_t, uint8_t)
Public Attributes
SensorSettings settings
SensorCalibration calibration
int32_t t_fine
Detailed Description
Definition at line 143 of file CoolSparkFunBME280.h.
Constructor & Destructor Documentation
BME280()
BME280::BME280 (void)
Definition at line 42 of file CoolSparkFunBME280.cpp.
References SensorSettings::chipSelectPin, SensorSettings::commInterface, SensorSettings::humidOverSample, I2C_MODE, SensorSettings::I2CAddress, SensorSettings::pressOverSample, SensorSettings::runMode, settings, and SensorSettings::tempOverSample.
Member Function Documentation
begin()
uint8_t BME280::begin (void)
Definition at line 69 of file CoolSparkFunBME280.cpp.
References BME280_CONFIG_REG, BME280_CTRL_HUMIDITY_REG, BME280_CTRL_MEAS_REG, BME280_DIG_H1_REG, BME280_DIG_H2_LSB_REG, BME280_DIG_H2_MSB_REG, BME280_DIG_H3_REG, BME280_DIG_H4_LSB_REG, BME280_DIG_H4_MSB_REG, BME280_DIG_H5_MSB_REG, BME280_DIG_H6_REG, BME280_DIG_P1_LSB_REG, BME280_DIG_P1_MSB_REG, BME280_DIG_P2_LSB_REG, BME280_DIG_P2_MSB_REG, BME280_DIG_P3_LSB_REG, BME280_DIG_P3_MSB_REG, BME280_DIG_P4_LSB_REG, BME280_DIG_P4_MSB_REG, BME280_DIG_P5_LSB_REG, BME280_DIG_P5_MSB_REG, BME280_DIG_P6_LSB_REG, BME280_DIG_P6_MSB_REG, BME280_DIG_P7_LSB_REG, BME280_DIG_P7_MSB_REG, BME280_DIG_P8_LSB_REG, BME280_DIG_P8_MSB_REG, BME280_DIG_P9_LSB_REG, BME280_DIG_P9_MSB_REG, BME280_DIG_T1_LSB_REG, BME280_DIG_T1_MSB_REG, BME280_DIG_T2_LSB_REG, BME280_DIG_T2_MSB_REG, BME280_DIG_T3_LSB_REG, BME280_DIG_T3_MSB_REG, calibration, SensorSettings::chipSelectPin, SensorSettings::commInterface, SensorCalibration::dig_H1, SensorCalibration::dig_H2, SensorCalibration::dig_H3, SensorCalibration::dig_H4, SensorCalibration::dig_H5, SensorCalibration::dig_H6, SensorCalibration::dig_P1, SensorCalibration::dig_P2, SensorCalibration::dig_P3, SensorCalibration::dig_P4, SensorCalibration::dig_P5, SensorCalibration::dig_P6, SensorCalibration::dig_P7, SensorCalibration::dig_P8, SensorCalibration::dig_P9, SensorCalibration::dig_T1, SensorCalibration::dig_T2, SensorCalibration::dig_T3, SensorSettings::filter, SensorSettings::humidOverSample, I2C_MODE, SensorSettings::pressOverSample, readRegister(), SensorSettings::runMode, settings, SPI_MODE, SensorSettings::tempOverSample, SensorSettings::tStandby, and writeRegister().
Referenced by CoolBoardSensors::begin().
reset()
void BME280::reset (void)
Definition at line 160 of file CoolSparkFunBME280.cpp.
References BME280_RST_REG, and writeRegister().
readFloatPressure()
float BME280::readFloatPressure (void)
Definition at line 171 of file CoolSparkFunBME280.cpp.
References BME280_PRESSURE_MSB_REG, calibration, SensorCalibration::dig_P1, SensorCalibration::dig_P2, SensorCalibration::dig_P3, SensorCalibration::dig_P4, SensorCalibration::dig_P5, SensorCalibration::dig_P6, SensorCalibration::dig_P7, SensorCalibration::dig_P8, SensorCalibration::dig_P9, readRegisterRegion(), and t_fine.
Referenced by CoolBoardSensors::read(), and readFloatAltitudeMeters().
readFloatAltitudeMeters()
float BME280::readFloatAltitudeMeters (void)
Definition at line 201 of file CoolSparkFunBME280.cpp.
References readFloatPressure().
Referenced by readFloatAltitudeFeet().
readFloatAltitudeFeet()
float BME280::readFloatAltitudeFeet (void)
Definition at line 210 of file CoolSparkFunBME280.cpp.
References readFloatAltitudeMeters().
readFloatHumidity()
float BME280::readFloatHumidity (void)
Definition at line 224 of file CoolSparkFunBME280.cpp.
References BME280_HUMIDITY_MSB_REG, calibration, SensorCalibration::dig_H1, SensorCalibration::dig_H2, SensorCalibration::dig_H3, SensorCalibration::dig_H4, SensorCalibration::dig_H5, SensorCalibration::dig_H6, readRegisterRegion(), and t_fine.
Referenced by CoolBoardSensors::read().
readTempC()
float BME280::readTempC (void)
Definition at line 254 of file CoolSparkFunBME280.cpp.
References BME280_TEMPERATURE_MSB_REG, calibration, SensorCalibration::dig_T1, SensorCalibration::dig_T2, SensorCalibration::dig_T3, readRegisterRegion(), and t_fine.
Referenced by CoolBoardSensors::read(), and readTempF().
readTempF()
float BME280::readTempF (void)
Definition at line 278 of file CoolSparkFunBME280.cpp.
References readTempC().
readRegisterRegion()
void BME280::readRegisterRegion (uint8_t * outputPointer, uint8_t offset, uint8_t length)
Definition at line 291 of file CoolSparkFunBME280.cpp.
References SensorSettings::chipSelectPin, SensorSettings::commInterface, I2C_MODE, SensorSettings::I2CAddress, settings, and SPI_MODE.
Referenced by readFloatHumidity(), readFloatPressure(), readRegisterInt16(), and readTempC().
readRegister()
uint8_t BME280::readRegister (uint8_t offset)
Definition at line 338 of file CoolSparkFunBME280.cpp.
References SensorSettings::chipSelectPin, SensorSettings::commInterface, I2C_MODE, SensorSettings::I2CAddress, settings, and SPI_MODE.
Referenced by begin(), and CoolBoardSensors::read().
readRegisterInt16()
int16_t BME280::readRegisterInt16 (uint8_t offset)
Definition at line 374 of file CoolSparkFunBME280.cpp.
References readRegisterRegion().
writeRegister()
void BME280::writeRegister (uint8_t offset, uint8_t dataToWrite)
Definition at line 383 of file CoolSparkFunBME280.cpp.
References SensorSettings::chipSelectPin, SensorSettings::commInterface, I2C_MODE, SensorSettings::I2CAddress, settings, and SPI_MODE.
Referenced by begin(), and reset().
Member Data Documentation
settings
SensorSettings BME280::settings
Definition at line 147 of file CoolSparkFunBME280.h.
Referenced by begin(), BME280(), readRegister(), readRegisterRegion(), CoolBoardSensors::setEnvSensorSettings(), and writeRegister().
calibration
SensorCalibration BME280::calibration
Definition at line 148 of file CoolSparkFunBME280.h.
Referenced by begin(), readFloatHumidity(), readFloatPressure(), and readTempC().
t_fine
int32_t BME280::t_fine
Definition at line 149 of file CoolSparkFunBME280.h.
Referenced by readFloatHumidity(), readFloatPressure(), and readTempC().
The documentation for this class was generated from the following files:
CoolSparkFunBME280.h
CoolSparkFunBME280.cpp