CoolBoard API: CoolBoardSensors Class Reference
CoolBoardSensors Class Reference
This class handles the On-Board Sensors.
#include <CoolBoardSensors.h>
Classes
struct airActive
struct lightActive
Public Member Functions
CoolBoardSensors ()
void begin ()
String read ()
void allActive ()
void end ()
bool config ()
void printConf ()
void setEnvSensorSettings (uint8_t commInterface=I2C_MODE, uint8_t I2CAddress=0x76, uint8_t runMode=3, uint8_t tStandby=0, uint8_t filter=0, uint8_t tempOverSample=1, uint8_t pressOverSample=1, uint8_t humidOverSample=1)
float readVBat ()
float readMoisture ()
Public Attributes
CoolSI114X lightSensor
BME280 envSensor
Private Attributes
struct CoolBoardSensors::lightActive lightDataActive
struct CoolBoardSensors::airActive airDataActive
const int EnMoisture = 13
const int AnMplex = 12
bool vbatActive =0
bool soilMoistureActive =0
Detailed Description
This class handles the On-Board Sensors.
Definition at line 48 of file CoolBoardSensors.h.
Class Documentation
CoolBoardSensors::airActive
struct CoolBoardSensors::airActive
airActive structure
set temperature to 1 to have temperature Readings
set humidity to 1 to have humidity Readings
set pressure to 1 to have pressure Readings
Definition at line 123 of file CoolBoardSensors.h.
Class Members
bool temperature
bool humidity
bool pressure
CoolBoardSensors::lightActive
struct CoolBoardSensors::lightActive
lightActive structure
set visible to 1 to have visibleLight Readings
set ir to 1 to have infraRed Readings
set uv to 1 to have ultraViolet Readings
Definition at line 106 of file CoolBoardSensors.h.
Class Members
bool visible
bool ir
bool uv
Constructor & Destructor Documentation
CoolBoardSensors()
CoolBoardSensors::CoolBoardSensors ()
CoolBoardSensors::CoolBoardSensors(): This Constructor is provided to init the different used pins
Definition at line 50 of file CoolBoardSensors.cpp.
References AnMplex, and EnMoisture.
Member Function Documentation
begin()
void CoolBoardSensors::begin ()
CoolBoardSensors::begin(): This method is provided to start the sensors that are on the sensor board
Definition at line 107 of file CoolBoardSensors.cpp.
References BME280::begin(), CoolSI114X::Begin(), envSensor, lightSensor, and setEnvSensorSettings().
Referenced by CoolBoard::begin().
read()
String CoolBoardSensors::read ()
CoolBoardSensors::read(): This method is provided to return the data read by the sensor board
Returns
a json string containing the sensors data
Definition at line 180 of file CoolBoardSensors.cpp.
References airDataActive, BME280_STAT_REG, CoolSI114X_COMMAND, CoolSI114X_IR_OVERFLOW, CoolSI114X_NOP, CoolSI114X_UV_OVERFLOW, CoolSI114X_VIS_OVERFLOW, envSensor, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, lightDataActive, lightSensor, CoolBoardSensors::airActive::pressure, BME280::readFloatHumidity(), BME280::readFloatPressure(), CoolSI114X::ReadIR(), readMoisture(), BME280::readRegister(), CoolSI114X::ReadResponseReg(), BME280::readTempC(), CoolSI114X::ReadUV(), readVBat(), CoolSI114X::ReadVisible(), soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, CoolBoardSensors::lightActive::visible, and CoolSI114X::WriteParamData().
Referenced by CoolBoard::readSensors().
allActive()
void CoolBoardSensors::allActive ()
CoolBoardSensors::allActive(): This method is provided to allow activation of all the sensor board sensors without passing by the configuration file/method
Definition at line 74 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
end()
void CoolBoardSensors::end ()
CoolBoardSensors::end(): This method is provided to end the sensors on the sensor board
Definition at line 159 of file CoolBoardSensors.cpp.
References CoolSI114X::DeInit(), and lightSensor.
config()
bool CoolBoardSensors::config ()
CoolBoardSensors::config(): This method is provided to configure the sensor board : -activate 1 -deactivate 0
Returns
true if configuration is successful, false otherwise
Definition at line 330 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
Referenced by CoolBoard::begin().
printConf()
void CoolBoardSensors::printConf ()
CoolBoardSensors::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 515 of file CoolBoardSensors.cpp.
References airDataActive, CoolBoardSensors::airActive::humidity, CoolBoardSensors::lightActive::ir, lightDataActive, CoolBoardSensors::airActive::pressure, soilMoistureActive, CoolBoardSensors::airActive::temperature, CoolBoardSensors::lightActive::uv, vbatActive, and CoolBoardSensors::lightActive::visible.
Referenced by CoolBoard::begin().
setEnvSensorSettings()
void CoolBoardSensors::setEnvSensorSettings (uint8_t commInterface = I2C_MODE, uint8_t I2CAddress = 0x76, uint8_t runMode = 3, uint8_t tStandby = 0, uint8_t filter = 0, uint8_t tempOverSample = 1, uint8_t pressOverSample = 1, uint8_t humidOverSample = 1)
CoolBoardSensors::setEnvSensorSetting(): This method is provided to set the enviornment sensor settings , if argument is ommitted , default value will be assigned
Definition at line 561 of file CoolBoardSensors.cpp.
References SensorSettings::commInterface, envSensor, SensorSettings::filter, SensorSettings::humidOverSample, SensorSettings::I2CAddress, SensorSettings::pressOverSample, SensorSettings::runMode, BME280::settings, SensorSettings::tempOverSample, and SensorSettings::tStandby.
Referenced by begin().
readVBat()
float CoolBoardSensors::readVBat ()
CoolBoardSensors::readVBat(): This method is provided to read the Battery Voltage.
Returns
a float representing the battery voltage
Definition at line 601 of file CoolBoardSensors.cpp.
References AnMplex.
Referenced by read().
readMoisture()
float CoolBoardSensors::readMoisture ()
CoolBoardSensors::readMoisture(): This method is provided to red the Soil Moisture
Returns
a float represnting the soil moisture
Definition at line 638 of file CoolBoardSensors.cpp.
References AnMplex, and EnMoisture.
Referenced by read().
Member Data Documentation
lightSensor
CoolSI114X CoolBoardSensors::lightSensor
SI114X light sensor instance
Definition at line 89 of file CoolBoardSensors.h.
Referenced by begin(), end(), and read().
envSensor
BME280 CoolBoardSensors::envSensor
BME280 environment sensor instance
Definition at line 94 of file CoolBoardSensors.h.
Referenced by begin(), read(), and setEnvSensorSettings().
lightDataActive
struct CoolBoardSensors::lightActive CoolBoardSensors::lightDataActive private
Referenced by allActive(), config(), printConf(), and read().
airDataActive
struct CoolBoardSensors::airActive CoolBoardSensors::airDataActive private
Referenced by allActive(), config(), printConf(), and read().
EnMoisture
const int CoolBoardSensors::EnMoisture = 13 private
Moisture Enable Pin
Definition at line 134 of file CoolBoardSensors.h.
Referenced by CoolBoardSensors(), and readMoisture().
AnMplex
const int CoolBoardSensors::AnMplex = 12 private
Analog Multiplexer LOW=Vbat , HIGH=Moisture
Definition at line 139 of file CoolBoardSensors.h.
Referenced by CoolBoardSensors(), readMoisture(), and readVBat().
vbatActive
bool CoolBoardSensors::vbatActive =0 private
set vbatActive to 1 to have battery voltage Readings
Definition at line 144 of file CoolBoardSensors.h.
Referenced by allActive(), config(), printConf(), and read().
soilMoistureActive
bool CoolBoardSensors::soilMoistureActive =0 private
set soilMoistureActive to 1 to have soil Moisture Readings
Definition at line 149 of file CoolBoardSensors.h.
Referenced by allActive(), config(), printConf(), and read().
The documentation for this class was generated from the following files:
CoolBoardSensors.h
CoolBoardSensors.cpp