CoolBoard API: CoolBoardActor Class Reference
CoolBoardActor Class Reference
This class manages the CoolBoardActor.
#include <CoolBoardActor.h>
Classes
struct state
Public Member Functions
void begin ()
void write (bool action)
String doAction (const char *data)
void normalAction (float measurment)
void invertedAction (float measurment)
void temporalActionOff ()
void temporalActionOn ()
void mixedTemporalActionOff (float measurment)
void mixedTemporalActionOn (float measurment)
void hourAction (int hour)
void mixedHourAction (int hour, float measurment)
void minuteAction (int minute)
void mixedMinuteAction (int minute, float measurment)
void hourMinuteAction (int hour, int minute)
void mixedHourMinuteAction (int hour, int minute, float measurment)
bool config ()
void printConf ()
Private Attributes
struct CoolBoardActor::state actor
const int pin = 15
Detailed Description
This class manages the CoolBoardActor.
Definition at line 44 of file CoolBoardActor.h.
Class Documentation
CoolBoardActor::state
struct CoolBoardActor::state
the Actor's state
Definition at line 87 of file CoolBoardActor.h.
Class Members
bool actif
actif flag set to 1 when using an actor set to 0 otherwise
bool temporal
temporal flag set to 1 to declare a temporal actor set to 0 otherwise
bool inverted
inverted flag set to 1 to declare an inverted actor set to 0 to declare a normal actor
String primaryType
"type":["temperature","hour"]
the primary type is related to the sensor's type (type[0])
if both types are present and valid, the actor is a mixedActor
String secondaryType
"type":["temperature","hour"]
the secondary type if present is hour or minute or hourMinute (type[1])
if both types are present and valid, the actor is a mixedActor
int rangeLow
"low":[20,5000,18,10]
rangeLow : this is the minimum at which the actor becomes actif (low[0])
unsigned long timeLow
"low":[20,5000,18,10]
timeLow : this is the time the actor is off in temporal mode (low[1]) (ms)
int hourLow
"low":[20,5000,18,10]
hour low :this is the hour when to turn off the actor in temporal/hour(hourMinute) mode (low[2])
int minuteLow
"low":[20,5000,18,10]
minute low :this is the minute when to turn off the actor in temporal/minute(hourMinute) mode (low[3])
int rangeHigh
"high":[30,2000,17,1]
rangeHigh : this is the maximum at which the actor becomes inactif(high[0])
unsigned long timeHigh
"high":[30,2000,17,1]
timeHigh : this is the time the actor is on in temporal mode(high[1]) (ms)
int hourHigh
"high":[30,2000,17,1]
hourHigh : this is the hour when to turn on the actor in temporal/hour(hourMinute) mode(high[2])
int minuteHigh
"high":[30,2000,17,1]
minuteHigh : this is the minute when to turn on the actor in temporal/minute(hourMinute) mode (high[3])
unsigned long actifTime
actifTime : period of Time spent actif , used in Temporal mode in ms
unsigned long inactifTime
inactifTime : period of Time spent inactif , used in Temporal mode in ms
Member Function Documentation
begin()
void CoolBoardActor::begin ()
CoolBoardActor::begin(): This method is provided to initialise the CoolBoardActor pin
Definition at line 48 of file CoolBoardActor.cpp.
References pin.
Referenced by CoolBoard::begin().
write()
void CoolBoardActor::write (bool action)
CoolBoardActor::write(action): This method is provided to write the given action to the CoolBoardActor.
Definition at line 71 of file CoolBoardActor.cpp.
References pin.
Referenced by hourAction(), hourMinuteAction(), invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), temporalActionOff(), temporalActionOn(), and CoolBoard::update().
doAction()
String CoolBoardActor::doAction (const char * data)
CoolBoardActor::doAction(sensor data): This method is provided to automate the CoolBoardActor.
The result action is the result of checking the different flags of the actor (actif , temporal ,inverted, primaryType and secondaryType) and the corresponding call to the appropriate helping method
Returns
a string of the actor's state
Definition at line 103 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, actor, hourAction(), hourMinuteAction(), CoolBoardActor::state::inverted, invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), pin, CoolBoardActor::state::primaryType, CoolBoardActor::state::secondaryType, CoolBoardActor::state::temporal, temporalActionOff(), and temporalActionOn().
Referenced by CoolBoard::offLineMode(), and CoolBoard::onLineMode().
normalAction()
void CoolBoardActor::normalAction (float measurment)
CoolBoardActor::normalAction(measured value): This method is provided to handle normal actors. it changes the action according to wether the measured value is: > rangeHigh (deactivate actor) or < rangeLow (activate actor)
Definition at line 555 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, and write().
Referenced by doAction().
invertedAction()
void CoolBoardActor::invertedAction (float measurment)
CoolBoardActor::invertedAction(measured value): This method is provided to handle inverted actors. it changes the action according to wether the measured value is:
rangeHigh (activate actor)
< rangeLow (deactivate actor)
Definition at line 612 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, and write().
Referenced by doAction().
temporalActionOff()
void CoolBoardActor::temporalActionOff ()
CoolBoardActor::temporalActionOff(): This method is provided to handle temporal actors. it changes the action according to:
currentTime - startTime > timeHigh : deactivate actor
Definition at line 667 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, CoolBoardActor::state::actifTime, actor, CoolBoardActor::state::inactifTime, CoolBoardActor::state::timeHigh, and write().
Referenced by doAction().
temporalActionOn()
void CoolBoardActor::temporalActionOn ()
CoolBoardActor::temporalActionOn(): This method is provided to handle temporal actors. it changes the action according to :
currentTime - stopTime > timeLow : activate actor
Definition at line 804 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, CoolBoardActor::state::actifTime, actor, CoolBoardActor::state::inactifTime, CoolBoardActor::state::timeLow, and write().
Referenced by doAction().
mixedTemporalActionOff()
void CoolBoardActor::mixedTemporalActionOff (float measurment)
CoolBoardActor::mixedTemporalActionOff(measured value): This method is provided to handle mixed temporal actors. it changes the action according to:
currentTime - startTime >= timeHigh : measured value >= rangeHigh : deactivate actor measured value < rangeHigh : activate actor
Definition at line 718 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, CoolBoardActor::state::actifTime, actor, CoolBoardActor::state::inactifTime, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::timeHigh, and write().
Referenced by doAction().
mixedTemporalActionOn()
void CoolBoardActor::mixedTemporalActionOn (float measurment)
CoolBoardActor::mixedTemporalActionOn(measured value): This method is provided to handle mixed temporal actors. it changes the action according to :
currentTime - stopTime > timeLow : measured value >= rangeLow : deactivate actor measured value < rangeLow : activate actor
Definition at line 856 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, CoolBoardActor::state::actifTime, actor, CoolBoardActor::state::inactifTime, CoolBoardActor::state::rangeLow, CoolBoardActor::state::timeLow, and write().
Referenced by doAction().
hourAction()
void CoolBoardActor::hourAction (int hour)
CoolBoardActor::hourAction(current hour): This method is provided to handle hour actors. it changes the action according to:
hour >= hourLow : deactivate the actor hour >= hourHigh : activate the actor
Definition at line 945 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, and write().
Referenced by doAction().
mixedHourAction()
void CoolBoardActor::mixedHourAction (int hour, float measurment)
CoolBoardActor::mixedHourAction(current hour, measured value): This method is provided to handle mixed hour actors. it changes the action according to :
hour >= hourLow : -measuredValue >= rangeHigh : deactivate actor -measured < rangeHigh : activate actor
hour >= hourHigh : -measuredValue < rangeLow : activate actor -measuredValue >=rangeLow : activate actor
Definition at line 1006 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, and write().
Referenced by doAction().
minuteAction()
void CoolBoardActor::minuteAction (int minute)
CoolBoardActor::minteAction(current minute): This method is provided to handle minute actors. it changes the action according to:
minute >= minuteLow : deactivate the actor minute >= minuteHigh : activate the actor
Definition at line 1113 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, and write().
Referenced by doAction().
mixedMinuteAction()
void CoolBoardActor::mixedMinuteAction (int minute, float measurment)
CoolBoardActor::mixedMinuteAction(current minute, measured value): This method is provided to handle mixed minute actors. it changes the action according to :
minute >= minuteLow : -measuredValue >= rangeHigh : deactivate actor -measured < rangeHigh : activate actor
minute >= minuteHigh : -measuredValue < rangeLow : activate actor -measuredValue >=rangeLow : activate actor
Definition at line 1173 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, and write().
Referenced by doAction().
hourMinuteAction()
void CoolBoardActor::hourMinuteAction (int hour, int minute)
CoolBoardActor::minteAction(current hour,current minute): This method is provided to handle hour minute actors. it changes the action according to:
hour == hourLow : minute >= minuteLow : deactivate the actor
hour > hourLow : deactivate the actor
hour == hourHigh : minute >= minteHigh : activate the actor
hour > hourHigh : activate the actor
Definition at line 1289 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, and write().
Referenced by doAction().
mixedHourMinuteAction()
void CoolBoardActor::mixedHourMinuteAction (int hour, int minute, float measurment)
CoolBoardActor::minteAction(current hour,current minute , measured Value): This method is provided to handle hour minute actors. it changes the action according to:
hour == hourLow : minute >= minuteLow : measuredValue >= rangeHigh : deactivate actor measuredValue < rangeHigh : activate actor
hour > hourLow : measuredValue >= rangeHigh : deactivate actor measuredValue < rangeHigh : activate actor
hour == hourHigh : minute >= minteHigh : measuredValue >= rangeLow : deactivate actor measuredValue < rangeLow : activate actor
hour > hourHigh : measuredValue >= rangeLow : deactivate actor measuredValue < rangeLow : activate actor
Definition at line 1394 of file CoolBoardActor.cpp.
References actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, and write().
Referenced by doAction().
config()
bool CoolBoardActor::config ()
CoolBoardActor::config(): This method is provided to configure the CoolBoardActor with a configuration file
Returns
true if successful,false otherwise
Definition at line 281 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, CoolBoardActor::state::inverted, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, CoolBoardActor::state::primaryType, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, CoolBoardActor::state::secondaryType, CoolBoardActor::state::temporal, CoolBoardActor::state::timeHigh, and CoolBoardActor::state::timeLow.
Referenced by CoolBoard::begin().
printConf()
void CoolBoardActor::printConf ()
CoolBoardActor::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 481 of file CoolBoardActor.cpp.
References CoolBoardActor::state::actif, actor, CoolBoardActor::state::hourHigh, CoolBoardActor::state::hourLow, CoolBoardActor::state::inverted, CoolBoardActor::state::minuteHigh, CoolBoardActor::state::minuteLow, CoolBoardActor::state::primaryType, CoolBoardActor::state::rangeHigh, CoolBoardActor::state::rangeLow, CoolBoardActor::state::secondaryType, CoolBoardActor::state::temporal, CoolBoardActor::state::timeHigh, and CoolBoardActor::state::timeLow.
Referenced by CoolBoard::begin().
Member Data Documentation
actor
struct CoolBoardActor::state CoolBoardActor::actor private
Referenced by config(), doAction(), hourAction(), hourMinuteAction(), invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), printConf(), temporalActionOff(), and temporalActionOn().
pin
const int CoolBoardActor::pin = 15 private
pin Number value the only available pin that can be used to run a small actor is pin 15
Definition at line 205 of file CoolBoardActor.h.
Referenced by begin(), doAction(), and write().
The documentation for this class was generated from the following files:
CoolBoardActor.h
CoolBoardActor.cpp