CoolBoard API: CoolFileSystem Class Reference
CoolFileSystem Class Reference
This class handles the file system.
#include <CoolFileSystem.h>
Public Member Functions
bool begin ()
bool updateConfigFiles (String answer)
bool fileUpdate (String update, const char *path)
bool saveSensorData (const char *data)
bool saveSensorDataCSV (const char *data)
int isDataSaved ()
String * getSensorSavedData (int &size)
bool incrementsavedData ()
void getsavedData ()
Private Attributes
int savedData =0
int linesToSkip =0
Detailed Description
This class handles the file system.
Definition at line 46 of file CoolFileSystem.h.
Member Function Documentation
begin()
bool CoolFileSystem::begin ()
CoolFileSystem::begin(): This method is provided to start the SPIFFS object.
Returns
true if SPIFFS was initialized correctly, false otherwise
Definition at line 50 of file CoolFileSystem.cpp.
References getsavedData().
Referenced by CoolBoard::config().
updateConfigFiles()
bool CoolFileSystem::updateConfigFiles (String answer)
CoolFileSystem::updateConfigFiles(mqtt answer): This method is provided to update the configuration files when the appropriate mqtt answer is received
Returns
true if the files are updated correctly, false otherwise
Definition at line 390 of file CoolFileSystem.cpp.
References fileUpdate(), and temp.
Referenced by CoolBoard::update().
fileUpdate()
bool CoolFileSystem::fileUpdate (String update, const char * path)
CoolFileSystem::fileUpdate(update msg, file path): This method is provided to ensure the correct update for each configuration file in the File system
Returns
true if successful , false otherwise
Definition at line 1003 of file CoolFileSystem.cpp.
Referenced by updateConfigFiles().
saveSensorData()
bool CoolFileSystem::saveSensorData (const char * data)
CoolFileSystem::saveSensorData(data): This method is provided to save the data on the local memory when there is no internet available
increments the saved data flag when successful
Returns
true if the data was saved, false otherwise
Definition at line 81 of file CoolFileSystem.cpp.
References incrementsavedData(), savedData, and saveSensorDataCSV().
Referenced by CoolBoard::offLineMode().
saveSensorDataCSV()
bool CoolFileSystem::saveSensorDataCSV (const char * data)
CoolFileSystem::saveSensorDataCSV(data): This method is provided to save the data on the local memory in CSV format.
Returns
true if the data was saved, false otherwise
Definition at line 185 of file CoolFileSystem.cpp.
Referenced by saveSensorData().
isDataSaved()
int CoolFileSystem::isDataSaved ()
CoolFileSystem::isDataSaved(): This method is provided to report wether there is sensor data saved in the File System.
Returns
true if there is data saved, false otherwise
Definition at line 782 of file CoolFileSystem.cpp.
References savedData.
Referenced by CoolBoard::onLineMode().
getSensorSavedData()
String * CoolFileSystem::getSensorSavedData (int & lines)
CoolFileSystem::getSensorData(int &lines): This method is provided to return the sensor data saved in the File System 10 lines at a time
Returns
String array containing 50 first lines from the file modifies tge lines argument to reflect the number of lines left
Definition at line 842 of file CoolFileSystem.cpp.
References incrementsavedData(), linesToSkip, savedData, and temp.
Referenced by CoolBoard::onLineMode().
incrementsavedData()
bool CoolFileSystem::incrementsavedData ()
CoolFileSystem::incrementsavedData(): This method is provided to increment the savedData flag
Returns
true if successful , false otherwise
Definition at line 1152 of file CoolFileSystem.cpp.
References linesToSkip, and savedData.
Referenced by getSensorSavedData(), and saveSensorData().
getsavedData()
void CoolFileSystem::getsavedData ()
CoolFileSystem::getsavedData(): This method is provided to get the savedData flag from the file system
Definition at line 1202 of file CoolFileSystem.cpp.
References linesToSkip, savedData, and temp.
Referenced by begin().
Member Data Documentation
savedData
int CoolFileSystem::savedData =0 private
Number of lines to read when retrieving saved Data
Definition at line 74 of file CoolFileSystem.h.
Referenced by getsavedData(), getSensorSavedData(), incrementsavedData(), isDataSaved(), and saveSensorData().
linesToSkip
int CoolFileSystem::linesToSkip =0 private
Number of lines to Skip when retrieving saved Data
Definition at line 80 of file CoolFileSystem.h.
Referenced by getsavedData(), getSensorSavedData(), and incrementsavedData().
The documentation for this class was generated from the following files:
CoolFileSystem.h
CoolFileSystem.cpp