var annotated_dup =
[
    [ "Adafruit_ADS1015", "class_adafruit___a_d_s1015.html", "class_adafruit___a_d_s1015" ],
    [ "Adafruit_ADS1115", "class_adafruit___a_d_s1115.html", "class_adafruit___a_d_s1115" ],
    [ "Adafruit_TCS34725", "class_adafruit___t_c_s34725.html", "class_adafruit___t_c_s34725" ],
    [ "BaseExternalSensor", "class_base_external_sensor.html", "class_base_external_sensor" ],
    [ "BME280", "class_b_m_e280.html", "class_b_m_e280" ],
    [ "CoolBoard", "class_cool_board.html", "class_cool_board" ],
    [ "CoolBoardActor", "class_cool_board_actor.html", "class_cool_board_actor" ],
    [ "CoolBoardLed", "class_cool_board_led.html", "class_cool_board_led" ],
    [ "CoolBoardSensors", "class_cool_board_sensors.html", "class_cool_board_sensors" ],
    [ "CoolFileSystem", "class_cool_file_system.html", "class_cool_file_system" ],
    [ "CoolMQTT", "class_cool_m_q_t_t.html", "class_cool_m_q_t_t" ],
    [ "CoolPubSubClient", "class_cool_pub_sub_client.html", "class_cool_pub_sub_client" ],
    [ "CoolSI114X", "class_cool_s_i114_x.html", "class_cool_s_i114_x" ],
    [ "CoolTime", "class_cool_time.html", "class_cool_time" ],
    [ "CoolWifi", "class_cool_wifi.html", "class_cool_wifi" ],
    [ "ExternalSensor", "class_external_sensor.html", "class_external_sensor" ],
    [ "ExternalSensor< Adafruit_ADS1015 >", "class_external_sensor_3_01_adafruit___a_d_s1015_01_4.html", "class_external_sensor_3_01_adafruit___a_d_s1015_01_4" ],
    [ "ExternalSensor< Adafruit_ADS1115 >", "class_external_sensor_3_01_adafruit___a_d_s1115_01_4.html", "class_external_sensor_3_01_adafruit___a_d_s1115_01_4" ],
    [ "ExternalSensor< Adafruit_TCS34725 >", "class_external_sensor_3_01_adafruit___t_c_s34725_01_4.html", "class_external_sensor_3_01_adafruit___t_c_s34725_01_4" ],
    [ "ExternalSensor< DallasTemperature >", "class_external_sensor_3_01_dallas_temperature_01_4.html", "class_external_sensor_3_01_dallas_temperature_01_4" ],
    [ "ExternalSensor< NDIR_I2C >", "class_external_sensor_3_01_n_d_i_r___i2_c_01_4.html", "class_external_sensor_3_01_n_d_i_r___i2_c_01_4" ],
    [ "ExternalSensors", "class_external_sensors.html", "class_external_sensors" ],
    [ "Irene3000", "class_irene3000.html", "class_irene3000" ],
    [ "Jetpack", "class_jetpack.html", "class_jetpack" ],
    [ "NDIR_I2C", "class_n_d_i_r___i2_c.html", "class_n_d_i_r___i2_c" ],
    [ "SensorCalibration", "struct_sensor_calibration.html", "struct_sensor_calibration" ],
    [ "SensorSettings", "struct_sensor_settings.html", "struct_sensor_settings" ],
    [ "WiFiManager", "class_wi_fi_manager.html", "class_wi_fi_manager" ],
    [ "WiFiManagerParameter", "class_wi_fi_manager_parameter.html", "class_wi_fi_manager_parameter" ]
];