CoolBoard API: BaseExternalSensor Class Reference
BaseExternalSensor Class Reference
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism.
#include <ExternalSensor.h>
Public Member Functions
BaseExternalSensor ()
virtual uint8_t begin ()
virtual float read ()
virtual float read (int16_t *a, int16_t *b, int16_t *c, int16_t *d, int16_t *e, int16_t *f)
Detailed Description
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism.
Definition at line 52 of file ExternalSensor.h.
Constructor & Destructor Documentation
BaseExternalSensor()
BaseExternalSensor::BaseExternalSensor () inline
BaseExternalSensor(): Base class generic Constructor
Definition at line 60 of file ExternalSensor.h.
Member Function Documentation
begin()
virtual uint8_t BaseExternalSensor::begin () inline virtual
begin(): Base class virtual generic begin method
Returns
generic value as it's not supposed to be used
Reimplemented in ExternalSensor< Adafruit_ADS1115 >, ExternalSensor< Adafruit_ADS1015 >, ExternalSensor< Adafruit_TCS34725 >, ExternalSensor< DallasTemperature >, ExternalSensor< NDIR_I2C >, and ExternalSensor< T >.
Definition at line 80 of file ExternalSensor.h.
Referenced by ExternalSensors::begin().
read() [1/2]
virtual float BaseExternalSensor::read () inline virtual
read(): Base class virtual generic read method
Returns
generic value as it is not supposed to be used
Reimplemented in ExternalSensor< DallasTemperature >, ExternalSensor< NDIR_I2C >, and ExternalSensor< T >.
Definition at line 102 of file ExternalSensor.h.
Referenced by ExternalSensors::begin(), and ExternalSensors::read().
read() [2/2]
virtual float BaseExternalSensor::read (int16_t * a, int16_t * b, int16_t * c, int16_t * d, int16_t * e, int16_t * f) inline virtual
read(): Base class virtual generic read method
Returns
generic value as it is not supposed to be used
Reimplemented in ExternalSensor< Adafruit_ADS1115 >, ExternalSensor< Adafruit_ADS1015 >, and ExternalSensor< Adafruit_TCS34725 >.
Definition at line 123 of file ExternalSensor.h.
The documentation for this class was generated from the following file:
ExternalSensor.h