CoolBoard API: Jetpack Class Reference
Jetpack Class Reference
This class manages the Jetpack shield.
#include <Jetpack.h>
Classes
struct state
Public Member Functions
void begin ()
void write (byte action)
void writeBit (byte pin, bool state)
String doAction (const char *data)
void normalAction (int actorNumber, float measurment)
void invertedAction (int actorNumber, float measurment)
void temporalActionOff (int actorNumber)
void temporalActionOn (int actorNumber)
void mixedTemporalActionOff (int actorNumber, float measurment)
void mixedTemporalActionOn (int actorNumber, float measurment)
void hourAction (int actorNumber, int hour)
void mixedHourAction (int actorNumber, int hour, float measurment)
void minuteAction (int actorNumber, int minute)
void mixedMinuteAction (int actorNumber, int minute, float measurment)
void hourMinuteAction (int actorNumber, int hour, int minute)
void mixedHourMinuteAction (int actorNumber, int hour, int minute, float measurment)
bool config ()
void printConf ()
Private Attributes
byte action = B00000000
struct Jetpack::state actors [8]
const int clockPin = 4
const int dataPin = 15
const int EnI2C =5
Detailed Description
This class manages the Jetpack shield.
Definition at line 45 of file Jetpack.h.
Class Documentation
Jetpack::state
struct Jetpack::state
the Actor's state
Definition at line 95 of file Jetpack.h.
Class Members
bool actif
actif flag set to 1 when using an actor set to 0 otherwise
bool temporal
temporal flag set to 1 to declare a temporal actor set to 0 otherwise
bool inverted
inverted flag set to 1 to declare an inverted actor set to 0 to declare a normal actor
String primaryType
"type":["temperature","hour"]
the primary type is related to the sensor's type (type[0])
if both types are present and valid, the actor is a mixedActor
String secondaryType
"type":["temperature","hour"]
the secondary type if present is hour or minute or hourMinute (type[1])
if both types are present and valid, the actor is a mixedActor
int rangeLow
"low":[20,5000,18,10]
rangeLow : this is the minimum at which the actor becomes actif (low[0])
unsigned long timeLow
"low":[20,5000,18,10]
timeLow : this is the time the actor is off in temporal mode (low[1]) (ms)
int hourLow
"low":[20,5000,18,10]
hour low :this is the hour when to turn off the actor in temporal/hour(hourMinute) mode (low[2])
int minuteLow
"low":[20,5000,18,10]
minute low :this is the minute when to turn off the actor in temporal/minute(hourMinute) mode (low[3])
int rangeHigh
"high":[30,2000,17,1]
rangeHigh : this is the maximum at which the actor becomes inactif(high[0])
unsigned long timeHigh
"high":[30,2000,17,1]
timeHigh : this is the time the actor is on in temporal mode(high[1]) (ms)
int hourHigh
"high":[30,2000,17,1]
hourHigh : this is the hour when to turn on the actor in temporal/hour(hourMinute) mode(high[2])
int minuteHigh
"high":[30,2000,17,1]
minuteHigh : this is the minute when to turn on the actor in temporal/minute(hourMinute) mode (high[3])
unsigned long actifTime
actifTime : period of Time spent actif , used in Temporal mode in ms
unsigned long inactifTime
inactifTime : period of Time spent inactif , used in Temporal mode in ms
Member Function Documentation
begin()
void Jetpack::begin (void)
Jetpack::begin(): This method is provided to initialise the pin that control the Jetpack shield
Definition at line 50 of file Jetpack.cpp.
References clockPin, dataPin, and EnI2C.
Referenced by CoolBoard::begin().
write()
void Jetpack::write (byte action)
Jetpack::write(action): This method is provided to write the given action to the entire Jetpack action is a Byte (8 bits), each bit goes to an output. MSBFirst
Definition at line 77 of file Jetpack.cpp.
References action, clockPin, dataPin, and EnI2C.
Referenced by doAction().
writeBit()
void Jetpack::writeBit (byte pin, bool state)
Jetpack::writeBit(pin,state): This method is provided to write the given state to the given pin
Definition at line 108 of file Jetpack.cpp.
References action, clockPin, dataPin, and EnI2C.
Referenced by CoolBoard::update().
doAction()
String Jetpack::doAction (const char * data)
Jetpack::doAction(sensor data): This method is provided to automate the Jetpack.
The result action is the result of checking the different flags of an actor (actif , temporal ,inverted, primaryType and secondaryType) and the corresponding call to the appropriate helping method
Returns
a string of the current Jetpack state
Definition at line 147 of file Jetpack.cpp.
References action, actors, hourAction(), hourMinuteAction(), invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), temporalActionOff(), temporalActionOn(), and write().
Referenced by CoolBoard::offLineMode(), and CoolBoard::onLineMode().
normalAction()
void Jetpack::normalAction (int actorNumber, float measurment)
Jetpack::normalAction(actorNumber , measured value): This method is provided to handle normal actors. it changes the action according to wether the measured value is: > rangeHigh (deactivate actor) or < rangeLow (activate actor)
Definition at line 661 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
invertedAction()
void Jetpack::invertedAction (int actorNumber, float measurment)
Jetpack::invertedAction(actorNumber , measured value): This method is provided to handle inverted actors. it changes the action according to wether the measured value is:
rangeHigh (activate actor)
< rangeLow (deactivate actor)
Definition at line 718 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
temporalActionOff()
void Jetpack::temporalActionOff (int actorNumber)
Jetpack::temporalActionOff(actorNumber): This method is provided to handle temporal actors. it changes the action according to:
currentTime - startTime > timeHigh : deactivate actor
Definition at line 773 of file Jetpack.cpp.
References Jetpack::state::actif, action, actors, and Jetpack::state::inactifTime.
Referenced by doAction().
temporalActionOn()
void Jetpack::temporalActionOn (int actorNumber)
Jetpack::temporalActionOn(actorNumber): This method is provided to handle temporal actors. it changes the action according to :
currentTime - stopTime > timeLow : activate actor
Definition at line 910 of file Jetpack.cpp.
References Jetpack::state::actif, Jetpack::state::actifTime, action, and actors.
Referenced by doAction().
mixedTemporalActionOff()
void Jetpack::mixedTemporalActionOff (int actorNumber, float measurment)
Jetpack::mixedTemporalActionOff(actorNumber, measured value): This method is provided to handle mixed temporal actors. it changes the action according to:
currentTime - startTime >= timeHigh : measured value >= rangeHigh : deactivate actor measured value < rangeHigh : activate actor
Definition at line 824 of file Jetpack.cpp.
References Jetpack::state::actif, action, actors, and Jetpack::state::inactifTime.
Referenced by doAction().
mixedTemporalActionOn()
void Jetpack::mixedTemporalActionOn (int actorNumber, float measurment)
Jetpack::mixedTemporalActionOn(actorNumber, measured value): This method is provided to handle mixed temporal actors. it changes the action according to :
currentTime - stopTime > timeLow : measured value >= rangeLow : deactivate actor measured value < rangeLow : activate actor
Definition at line 962 of file Jetpack.cpp.
References Jetpack::state::actif, Jetpack::state::actifTime, action, and actors.
Referenced by doAction().
hourAction()
void Jetpack::hourAction (int actorNumber, int hour)
Jetpack::hourAction(actorNumber, current hour): This method is provided to handle hour actors. it changes the action according to:
hour >= hourLow : deactivate the actor hour >= hourHigh : activate the actor
Definition at line 1051 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
mixedHourAction()
void Jetpack::mixedHourAction (int actorNumber, int hour, float measurment)
Jetpack::mixedHourAction(actorNumber, current hour, measured value): This method is provided to handle mixed hour actors. it changes the action according to :
hour >= hourLow : -measuredValue >= rangeHigh : deactivate actor -measured < rangeHigh : activate actor
hour >= hourHigh : -measuredValue < rangeLow : activate actor -measuredValue >=rangeLow : activate actor
Definition at line 1112 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
minuteAction()
void Jetpack::minuteAction (int actorNumber, int minute)
Jetpack::minteAction(actorNumber, current minute): This method is provided to handle minute actors. it changes the action according to:
minute >= minuteLow : deactivate the actor minute >= minuteHigh : activate the actor
Definition at line 1219 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
mixedMinuteAction()
void Jetpack::mixedMinuteAction (int actorNumber, int minute, float measurment)
Jetpack::mixedMinuteAction(actorNumber, current minute, measured value): This method is provided to handle mixed minute actors. it changes the action according to :
minute >= minuteLow : -measuredValue >= rangeHigh : deactivate actor -measured < rangeHigh : activate actor
minute >= minuteHigh : -measuredValue < rangeLow : activate actor -measuredValue >=rangeLow : activate actor
Definition at line 1279 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
hourMinuteAction()
void Jetpack::hourMinuteAction (int actorNumber, int hour, int minute)
Jetpack::minteAction(actorNumber, current hour,current minute): This method is provided to handle hour minute actors. it changes the action according to:
hour == hourLow : minute >= minuteLow : deactivate the actor
hour > hourLow : deactivate the actor
hour == hourHigh : minute >= minteHigh : activate the actor
hour > hourHigh : activate the actor
Definition at line 1395 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
mixedHourMinuteAction()
void Jetpack::mixedHourMinuteAction (int actorNumber, int hour, int minute, float measurment)
Jetpack::minteAction(actorNumber, current hour,current minute , measured Value): This method is provided to handle hour minute actors. it changes the action according to:
hour == hourLow : minute >= minuteLow : measuredValue >= rangeHigh : deactivate actor measuredValue < rangeHigh : activate actor
hour > hourLow : measuredValue >= rangeHigh : deactivate actor measuredValue < rangeHigh : activate actor
hour == hourHigh : minute >= minteHigh : measuredValue >= rangeLow : deactivate actor measuredValue < rangeLow : activate actor
hour > hourHigh : measuredValue >= rangeLow : deactivate actor measuredValue < rangeLow : activate actor
Definition at line 1500 of file Jetpack.cpp.
References action, and actors.
Referenced by doAction().
config()
bool Jetpack::config ()
Jetpack::config(): This method is provided to configure the Jetpack with a configuration file
Returns
true if successful,false otherwise
Definition at line 331 of file Jetpack.cpp.
References Jetpack::state::actif, actors, Jetpack::state::hourHigh, Jetpack::state::hourLow, Jetpack::state::inverted, Jetpack::state::minuteHigh, Jetpack::state::minuteLow, Jetpack::state::primaryType, Jetpack::state::rangeHigh, Jetpack::state::rangeLow, Jetpack::state::secondaryType, Jetpack::state::temporal, Jetpack::state::timeHigh, and Jetpack::state::timeLow.
Referenced by CoolBoard::begin().
printConf()
void Jetpack::printConf ()
Jetpack::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 567 of file Jetpack.cpp.
References actors.
Referenced by CoolBoard::begin().
Member Data Documentation
action
byte Jetpack::action = B00000000 private
the Jetpack's Action
Definition at line 90 of file Jetpack.h.
Referenced by doAction(), hourAction(), hourMinuteAction(), invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), temporalActionOff(), temporalActionOn(), write(), and writeBit().
actors
struct Jetpack::state Jetpack::actors[8] private
Referenced by config(), doAction(), hourAction(), hourMinuteAction(), invertedAction(), minuteAction(), mixedHourAction(), mixedHourMinuteAction(), mixedMinuteAction(), mixedTemporalActionOff(), mixedTemporalActionOn(), normalAction(), printConf(), temporalActionOff(), and temporalActionOn().
clockPin
const int Jetpack::clockPin = 4 private
clock pin for the shift register
Definition at line 211 of file Jetpack.h.
Referenced by begin(), write(), and writeBit().
dataPin
const int Jetpack::dataPin = 15 private
data pin for the shift register
Definition at line 216 of file Jetpack.h.
Referenced by begin(), write(), and writeBit().
EnI2C
const int Jetpack::EnI2C =5 private
I2C Enable pin
Definition at line 221 of file Jetpack.h.
Referenced by begin(), write(), and writeBit().
The documentation for this class was generated from the following files:
Jetpack.h
Jetpack.cpp