CoolBoard API: CoolSI114X Class Reference
CoolSI114X Class Reference
#include <CoolSI114X.h>
Public Member Functions
bool Begin (void)
void Reset (void)
void DeInit (void)
uint8_t ReadParamData (uint8_t Reg)
uint8_t WriteParamData (uint8_t Reg, uint8_t Value)
uint16_t ReadVisible (void)
uint16_t ReadIR (void)
uint16_t ReadProximity (uint8_t PSn)
uint16_t ReadUV (void)
uint8_t ReadResponseReg (void)
Private Member Functions
void WriteByte (uint8_t Reg, uint8_t Value)
uint8_t ReadByte (uint8_t Reg)
uint16_t ReadHalfWord (uint8_t Reg)
Detailed Description
Definition at line 170 of file CoolSI114X.h.
Member Function Documentation
Begin()
bool CoolSI114X::Begin (void)
Definition at line 91 of file CoolSI114X.cpp.
References CoolSI114X_PART_ID, DeInit(), ReadByte(), and Reset().
Referenced by CoolBoardSensors::begin().
Reset()
void CoolSI114X::Reset (void)
Definition at line 113 of file CoolSI114X.cpp.
References CoolSI114X_COMMAND, CoolSI114X_HW_KEY, CoolSI114X_INT_CFG, CoolSI114X_IRQ_ENABLE, CoolSI114X_IRQ_MODE1, CoolSI114X_IRQ_MODE2, CoolSI114X_IRQ_STATUS, CoolSI114X_MEAS_RATE0, CoolSI114X_MEAS_RATE1, CoolSI114X_RESET, and WriteByte().
Referenced by Begin().
DeInit()
void CoolSI114X::DeInit (void)
Definition at line 41 of file CoolSI114X.cpp.
References CoolSI114X_ADC_COUNTER_511ADCCLK, CoolSI114X_ADC_GAIN_DIV1, CoolSI114X_ADC_MISC_ADC_RAWADC, CoolSI114X_ADC_MISC_HIGHRANGE, CoolSI114X_ADCMUX_LARGE_IR, CoolSI114X_ALS_IR_ADC_COUNTER, CoolSI114X_ALS_IR_ADC_GAIN, CoolSI114X_ALS_IR_ADC_MISC, CoolSI114X_ALS_VIS_ADC_COUNTER, CoolSI114X_ALS_VIS_ADC_GAIN, CoolSI114X_ALS_VIS_ADC_MISC, CoolSI114X_CHLIST, CoolSI114X_CHLIST_ENALSIR, CoolSI114X_CHLIST_ENALSVIS, CoolSI114X_CHLIST_ENPS1, CoolSI114X_CHLIST_ENUV, CoolSI114X_COMMAND, CoolSI114X_INT_CFG, CoolSI114X_INT_CFG_INTOE, CoolSI114X_IRQ_ENABLE, CoolSI114X_IRQEN_ALS, CoolSI114X_LED_CURRENT_22MA, CoolSI114X_MEAS_RATE0, CoolSI114X_PS1_ADCMUX, CoolSI114X_PS_ADC_COUNTER, CoolSI114X_PS_ADC_GAIN, CoolSI114X_PS_ADC_MISC, CoolSI114X_PS_LED21, CoolSI114X_PSALS_AUTO, CoolSI114X_PSLED12_SELECT, CoolSI114X_PSLED12_SELECT_PS1_LED1, CoolSI114X_UCOEFF0, CoolSI114X_UCOEFF1, CoolSI114X_UCOEFF2, CoolSI114X_UCOEFF3, WriteByte(), and WriteParamData().
Referenced by Begin(), and CoolBoardSensors::end().
ReadParamData()
uint8_t CoolSI114X::ReadParamData (uint8_t Reg)
Definition at line 170 of file CoolSI114X.cpp.
References CoolSI114X_COMMAND, CoolSI114X_QUERY, CoolSI114X_RD, ReadByte(), and WriteByte().
WriteParamData()
uint8_t CoolSI114X::WriteParamData (uint8_t Reg, uint8_t Value)
Definition at line 179 of file CoolSI114X.cpp.
References CoolSI114X_COMMAND, CoolSI114X_RD, CoolSI114X_SET, CoolSI114X_WR, ReadByte(), and WriteByte().
Referenced by DeInit(), and CoolBoardSensors::read().
ReadVisible()
uint16_t CoolSI114X::ReadVisible (void)
Definition at line 192 of file CoolSI114X.cpp.
References CoolSI114X_ALS_VIS_DATA0, and ReadHalfWord().
Referenced by CoolBoardSensors::read().
ReadIR()
uint16_t CoolSI114X::ReadIR (void)
Definition at line 200 of file CoolSI114X.cpp.
References CoolSI114X_ALS_IR_DATA0, and ReadHalfWord().
Referenced by CoolBoardSensors::read().
ReadProximity()
uint16_t CoolSI114X::ReadProximity (uint8_t PSn)
Definition at line 208 of file CoolSI114X.cpp.
References ReadHalfWord().
ReadUV()
uint16_t CoolSI114X::ReadUV (void)
Definition at line 217 of file CoolSI114X.cpp.
References CoolSI114X_AUX_DATA0_UVINDEX0, and ReadHalfWord().
Referenced by CoolBoardSensors::read().
ReadResponseReg()
uint8_t CoolSI114X::ReadResponseReg (void)
Definition at line 226 of file CoolSI114X.cpp.
References CoolSI114X_RESPONSE, and ReadByte().
Referenced by CoolBoardSensors::read().
WriteByte()
void CoolSI114X::WriteByte (uint8_t Reg, uint8_t Value) private
Definition at line 132 of file CoolSI114X.cpp.
References CoolSI114X_ADDR.
Referenced by DeInit(), ReadParamData(), Reset(), and WriteParamData().
ReadByte()
uint8_t CoolSI114X::ReadByte (uint8_t Reg) private
Definition at line 143 of file CoolSI114X.cpp.
References CoolSI114X_ADDR.
Referenced by Begin(), ReadParamData(), ReadResponseReg(), and WriteParamData().
ReadHalfWord()
uint16_t CoolSI114X::ReadHalfWord (uint8_t Reg) private
Definition at line 155 of file CoolSI114X.cpp.
References CoolSI114X_ADDR.
Referenced by ReadIR(), ReadProximity(), ReadUV(), and ReadVisible().
The documentation for this class was generated from the following files:
CoolSI114X.h
CoolSI114X.cpp