CoolBoard API: Adafruit_ADS1015 Class Reference
Adafruit_ADS1015 Class Reference
#include <CoolAdafruit_ADS1015.h>
Public Member Functions
Adafruit_ADS1015 (uint8_t i2cAddress=ADS1015_ADDRESS)
Instantiates a new ADS1015 class w/appropriate properties.
void begin (void)
Sets up the HW (reads coefficients values, etc.)
uint16_t readADC_SingleEnded (uint8_t channel)
Gets a single-ended ADC reading from the specified channel.
int16_t readADC_Differential_0_1 (void)
Reads the conversion results, measuring the voltage difference between the P (AIN0) and N (AIN1) input. Generates a signed value since the difference can be either positive or negative.
int16_t readADC_Differential_2_3 (void)
Reads the conversion results, measuring the voltage difference between the P (AIN2) and N (AIN3) input. Generates a signed value since the difference can be either positive or negative.
void startComparator_SingleEnded (uint8_t channel, int16_t threshold)
Sets up the comparator to operate in basic mode, causing the ALERT/RDY pin to assert (go from high to low) when the ADC value exceeds the specified threshold.
int16_t getLastConversionResults ()
In order to clear the comparator, we need to read the conversion results. This function reads the last conversion results without changing the config value.
void setGain (adsGain_t gain)
Sets the gain and input voltage range.
adsGain_t getGain (void)
Gets a gain and input voltage range.
Protected Attributes
uint8_t m_i2cAddress
uint8_t m_conversionDelay
uint8_t m_bitShift
adsGain_t m_gain
Detailed Description
Definition at line 119 of file CoolAdafruit_ADS1015.h.
Constructor & Destructor Documentation
Adafruit_ADS1015()
Adafruit_ADS1015::Adafruit_ADS1015 (uint8_t i2cAddress = ADS1015_ADDRESS)
Instantiates a new ADS1015 class w/appropriate properties.
Definition at line 88 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_CONVERSIONDELAY, GAIN_TWOTHIRDS, m_bitShift, m_conversionDelay, m_gain, and m_i2cAddress.
Member Function Documentation
begin()
void Adafruit_ADS1015::begin (void)
Sets up the HW (reads coefficients values, etc.)
Definition at line 114 of file CoolAdafruit_ADS1015.cpp.
Referenced by Irene3000::begin().
readADC_SingleEnded()
uint16_t Adafruit_ADS1015::readADC_SingleEnded (uint8_t channel)
Gets a single-ended ADC reading from the specified channel.
Definition at line 143 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_SINGLE_0, ADS1015_REG_CONFIG_MUX_SINGLE_1, ADS1015_REG_CONFIG_MUX_SINGLE_2, ADS1015_REG_CONFIG_MUX_SINGLE_3, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister().
Referenced by Irene3000::calibratepH4(), Irene3000::calibratepH7(), Irene3000::readADSChannel2(), Irene3000::readButton(), Irene3000::readPh(), and Irene3000::readTemp().
readADC_Differential_0_1()
int16_t Adafruit_ADS1015::readADC_Differential_0_1 (void)
Reads the conversion results, measuring the voltage difference between the P (AIN0) and N (AIN1) input. Generates a signed value since the difference can be either positive or negative.
Definition at line 199 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_DIFF_0_1, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister().
readADC_Differential_2_3()
int16_t Adafruit_ADS1015::readADC_Differential_2_3 (void)
Reads the conversion results, measuring the voltage difference between the P (AIN2) and N (AIN3) input. Generates a signed value since the difference can be either positive or negative.
Definition at line 250 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_CONFIG_CLAT_NONLAT, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_NONE, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_SINGLE, ADS1015_REG_CONFIG_MUX_DIFF_2_3, ADS1015_REG_CONFIG_OS_SINGLE, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_gain, m_i2cAddress, readRegister(), and writeRegister().
startComparator_SingleEnded()
void Adafruit_ADS1015::startComparator_SingleEnded (uint8_t channel, int16_t threshold)
Sets up the comparator to operate in basic mode, causing the ALERT/RDY pin to assert (go from high to low) when the ADC value exceeds the specified threshold.
This will also set the ADC in continuous conversion mode.
Definition at line 302 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_CONFIG_CLAT_LATCH, ADS1015_REG_CONFIG_CMODE_TRAD, ADS1015_REG_CONFIG_CPOL_ACTVLOW, ADS1015_REG_CONFIG_CQUE_1CONV, ADS1015_REG_CONFIG_DR_1600SPS, ADS1015_REG_CONFIG_MODE_CONTIN, ADS1015_REG_CONFIG_MUX_SINGLE_0, ADS1015_REG_CONFIG_MUX_SINGLE_1, ADS1015_REG_CONFIG_MUX_SINGLE_2, ADS1015_REG_CONFIG_MUX_SINGLE_3, ADS1015_REG_POINTER_CONFIG, ADS1015_REG_POINTER_HITHRESH, m_bitShift, m_gain, m_i2cAddress, and writeRegister().
getLastConversionResults()
int16_t Adafruit_ADS1015::getLastConversionResults ()
In order to clear the comparator, we need to read the conversion results. This function reads the last conversion results without changing the config value.
Definition at line 348 of file CoolAdafruit_ADS1015.cpp.
References ADS1015_REG_POINTER_CONVERT, m_bitShift, m_conversionDelay, m_i2cAddress, and readRegister().
setGain()
void Adafruit_ADS1015::setGain (adsGain_t gain)
Sets the gain and input voltage range.
Definition at line 123 of file CoolAdafruit_ADS1015.cpp.
References m_gain.
Referenced by Irene3000::setGain().
getGain()
adsGain_t Adafruit_ADS1015::getGain (void)
Gets a gain and input voltage range.
Definition at line 133 of file CoolAdafruit_ADS1015.cpp.
References m_gain.
Member Data Documentation
m_i2cAddress
uint8_t Adafruit_ADS1015::m_i2cAddress protected
Definition at line 123 of file CoolAdafruit_ADS1015.h.
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), and startComparator_SingleEnded().
m_conversionDelay
uint8_t Adafruit_ADS1015::m_conversionDelay protected
Definition at line 124 of file CoolAdafruit_ADS1015.h.
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), and readADC_SingleEnded().
m_bitShift
uint8_t Adafruit_ADS1015::m_bitShift protected
Definition at line 125 of file CoolAdafruit_ADS1015.h.
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getLastConversionResults(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), and startComparator_SingleEnded().
m_gain
adsGain_t Adafruit_ADS1015::m_gain protected
Definition at line 126 of file CoolAdafruit_ADS1015.h.
Referenced by Adafruit_ADS1015(), Adafruit_ADS1115::Adafruit_ADS1115(), getGain(), readADC_Differential_0_1(), readADC_Differential_2_3(), readADC_SingleEnded(), setGain(), and startComparator_SingleEnded().
The documentation for this class was generated from the following files:
CoolAdafruit_ADS1015.h
CoolAdafruit_ADS1015.cpp