CoolBoard API: NDIR_I2C Class Reference
NDIR_I2C Class Reference
#include <CoolNDIR_I2C.h>
Public Member Functions
NDIR_I2C (uint8_t i2c_addr)
uint8_t begin ()
uint8_t measure ()
Public Attributes
uint8_t i2c_addr
uint32_t ppm
Private Member Functions
uint8_t send (uint8_t *pdata, uint8_t n)
uint8_t receive (uint8_t *pbuf, uint8_t n)
uint8_t read_register (uint8_t reg_addr, uint8_t *pval)
uint8_t write_register (uint8_t reg_addr, uint8_t *pdata, uint8_t n)
uint8_t write_register (uint8_t reg_addr, uint8_t val)
uint8_t parse (uint8_t *pbuf)
Static Private Attributes
static uint8_t cmd_measure [9] = {0xFF,0x01,0x9C,0x00,0x00,0x00,0x00,0x00,0x63}
Detailed Description
Definition at line 27 of file CoolNDIR_I2C.h.
Constructor & Destructor Documentation
NDIR_I2C()
NDIR_I2C::NDIR_I2C (uint8_t i2c_addr)
Definition at line 77 of file CoolNDIR_I2C.cpp.
References i2c_addr.
Member Function Documentation
begin()
uint8_t NDIR_I2C::begin (void)
Definition at line 87 of file CoolNDIR_I2C.cpp.
References DLH, DLL, FCR, i2c_addr, IOCONTROL, LCR, measure(), WIRE, and write_register().
measure()
uint8_t NDIR_I2C::measure ()
Definition at line 111 of file CoolNDIR_I2C.cpp.
References cmd_measure, FCR, i2c_addr, parse(), receive(), send(), and write_register().
Referenced by begin().
send()
uint8_t NDIR_I2C::send (uint8_t * pdata, uint8_t n) private
Definition at line 151 of file CoolNDIR_I2C.cpp.
References read_register(), THR, TXLVL, and write_register().
Referenced by measure().
receive()
uint8_t NDIR_I2C::receive (uint8_t * pbuf, uint8_t n) private
Definition at line 166 of file CoolNDIR_I2C.cpp.
References i2c_addr, read_register(), RECEIVE_TIMEOUT, RHR, RXLVL, and WIRE.
Referenced by measure().
read_register()
uint8_t NDIR_I2C::read_register (uint8_t reg_addr, uint8_t * pval) private
Definition at line 208 of file CoolNDIR_I2C.cpp.
References i2c_addr, and WIRE.
Referenced by receive(), and send().
write_register() [1/2]
uint8_t NDIR_I2C::write_register (uint8_t reg_addr, uint8_t * pdata, uint8_t n) private
Definition at line 228 of file CoolNDIR_I2C.cpp.
References i2c_addr, and WIRE.
Referenced by begin(), measure(), send(), and write_register().
write_register() [2/2]
uint8_t NDIR_I2C::write_register (uint8_t reg_addr, uint8_t val) private
Definition at line 248 of file CoolNDIR_I2C.cpp.
References write_register().
parse()
uint8_t NDIR_I2C::parse (uint8_t * pbuf) private
Definition at line 133 of file CoolNDIR_I2C.cpp.
References ppm.
Referenced by measure().
Member Data Documentation
i2c_addr
uint8_t NDIR_I2C::i2c_addr
Definition at line 31 of file CoolNDIR_I2C.h.
Referenced by begin(), measure(), NDIR_I2C(), read_register(), receive(), and write_register().
ppm
uint32_t NDIR_I2C::ppm
Definition at line 32 of file CoolNDIR_I2C.h.
Referenced by parse().
cmd_measure
uint8_t NDIR_I2C::cmd_measure = {0xFF,0x01,0x9C,0x00,0x00,0x00,0x00,0x00,0x63} static private
Definition at line 38 of file CoolNDIR_I2C.h.
Referenced by measure().
The documentation for this class was generated from the following files:
CoolNDIR_I2C.h
CoolNDIR_I2C.cpp