CoolBoard API: CoolWifi Class Reference
CoolWifi Class Reference
This class manages the WiFi connection .
#include <CoolWifi.h>
Public Member Functions
void begin ()
bool config ()
bool config (String ssid[], String pass[], int wifiNumber, int APTimeOut, bool nomad)
wl_status_t connect ()
wl_status_t connectWifiMulti ()
wl_status_t connectAP ()
wl_status_t state ()
void printConf ()
bool addWifi (String ssid, String pass="")
Private Attributes
ESP8266WiFiMulti wifiMulti
int wifiCount =0
String ssid [50] ={"0"}
String pass [50] ={"0"}
int timeOut =0
bool nomad =0
Detailed Description
This class manages the WiFi connection .
Definition at line 52 of file CoolWifi.h.
Member Function Documentation
begin()
void CoolWifi::begin ()
CoolWifi::begin(): This method is provided to set the wifiMulti Access points and the wifiManager time out
Definition at line 51 of file CoolWifi.cpp.
References pass, ssid, wifiCount, and wifiMulti.
Referenced by CoolBoard::begin().
config() [1/2]
bool CoolWifi::config ()
CoolWifi::config(): This method is provided to set the wifi parameters : -ssid -pass -AP timeOut -wifiCount
Returns
true if successful,false otherwise
Definition at line 297 of file CoolWifi.cpp.
References nomad, pass, ssid, timeOut, and wifiCount.
Referenced by CoolBoard::begin().
config() [2/2]
bool CoolWifi::config (String ssid[], String pass[], int wifiNumber, int APTimeOut, bool nomad)
CoolWifi::config(ssid array, pass array, number of wifis, AP timeout,nomad flag); This method is provided to configure the Wifi without SPIFFS
Returns
true if successfull, false otherwise
Definition at line 472 of file CoolWifi.cpp.
References nomad, timeOut, and wifiCount.
connect()
wl_status_t CoolWifi::connect ()
CoolWifi::connect(): This method is provided to connect to the strongest WiFi in the provided list of wiFis. If none are found , it starts the AP mode.
Returns
wifi state
Definition at line 104 of file CoolWifi.cpp.
References connectAP(), connectWifiMulti(), nomad, and wifiCount.
Referenced by CoolBoard::connect().
connectWifiMulti()
wl_status_t CoolWifi::connectWifiMulti ()
CoolWifi::connectWifiMulti() This function is provided to run the WifiMulti part of the Wifi connection process
Returns
wifi state
Definition at line 181 of file CoolWifi.cpp.
References wifiMulti.
Referenced by connect().
connectAP()
wl_status_t CoolWifi::connectAP ()
CoolWifi::connectAP() This function is provided to run the WifiManager part of the Wifi connection process
Returns
wifi state
Definition at line 231 of file CoolWifi.cpp.
References addWifi(), WiFiManager::autoConnect(), WiFiManager::setRemoveDuplicateAPs(), WiFiManager::setTimeout(), and timeOut.
Referenced by connect(), and CoolBoard::offLineMode().
state()
wl_status_t CoolWifi::state ()
CoolWifi::state(): This method is provided to return the Wifi client's state.
Returns
wifi client state: WL_NO_SHIELD = 255, WL_IDLE_STATUS = 0, WL_NO_SSID_AVAIL = 1, WL_SCAN_COMPLETED = 2, WL_CONNECTED = 3, WL_CONNECT_FAILED = 4, WL_CONNECTION_LOST = 5, WL_DISCONNECTED = 6
Definition at line 81 of file CoolWifi.cpp.
Referenced by CoolBoard::connect(), CoolBoard::isConnected(), and CoolBoard::offLineMode().
printConf()
void CoolWifi::printConf ()
CoolWifi::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 515 of file CoolWifi.cpp.
References nomad, ssid, timeOut, and wifiCount.
Referenced by CoolBoard::begin().
addWifi()
bool CoolWifi::addWifi (String ssid, String pass = "")
CoolWifi::addWifi(ssid,pass) This method is provided to add new WiFi detected by the WiFiManager to the jsonConfig(if used)
Returns
true if successfull , false otherwise
Definition at line 570 of file CoolWifi.cpp.
References pass, ssid, timeOut, and wifiCount.
Referenced by connectAP().
Member Data Documentation
wifiMulti
ESP8266WiFiMulti CoolWifi::wifiMulti private
ESP8266WiFiMulti instance
Definition at line 79 of file CoolWifi.h.
Referenced by begin(), and connectWifiMulti().
wifiCount
int CoolWifi::wifiCount =0 private
number of saved WiFi's
Definition at line 84 of file CoolWifi.h.
Referenced by addWifi(), begin(), config(), connect(), and printConf().
ssid
String CoolWifi::ssid[50] ={"0"} private
WiFi SSID Array
Definition at line 89 of file CoolWifi.h.
Referenced by addWifi(), begin(), config(), and printConf().
pass
String CoolWifi::pass[50] ={"0"} private
WiFi PASS Array
Definition at line 94 of file CoolWifi.h.
Referenced by addWifi(), begin(), and config().
timeOut
int CoolWifi::timeOut =0 private
WiFi Access Point TimeOut Value in Seconds
Definition at line 99 of file CoolWifi.h.
Referenced by addWifi(), config(), connectAP(), and printConf().
nomad
bool CoolWifi::nomad =0 private
nomad Mode Flag in Nomad Mode , the Wifi Access Point will Only Lunch on Start when there's NO saved wifis (wifiCount = 0) After that, the Wifi will ONLY try to connect to known Wifis via WifiMulti
Definition at line 108 of file CoolWifi.h.
Referenced by config(), connect(), and printConf().
The documentation for this class was generated from the following files:
CoolWifi.h
CoolWifi.cpp