.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/extras Directory Reference" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/extras Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBparse\&.js\fP"
.br
.ti -1c
.RI "file \fBtemplate\&.h\fP"
.br
.in -1c
