.TH "Adafruit_ADS1115" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Adafruit_ADS1115
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolAdafruit_ADS1015\&.h>\fP
.PP
Inherits \fBAdafruit_ADS1015\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdafruit_ADS1115\fP (uint8_t i2cAddress=\fBADS1015_ADDRESS\fP)"
.br
.RI "Instantiates a new ADS1115 class w/appropriate properties\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 143 of file CoolAdafruit_ADS1015\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Adafruit_ADS1115::Adafruit_ADS1115 (uint8_t i2cAddress = \fC\fBADS1015_ADDRESS\fP\fP)"

.PP
Instantiates a new ADS1115 class w/appropriate properties\&. 
.PP
Definition at line 101 of file CoolAdafruit_ADS1015\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
