.TH "BaseExternalSensor" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseExternalSensor \- This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ExternalSensor\&.h>\fP
.PP
Inherited by \fBExternalSensor< T >\fP, \fBExternalSensor< Adafruit_ADS1015 >\fP, \fBExternalSensor< Adafruit_ADS1115 >\fP, \fBExternalSensor< Adafruit_TCS34725 >\fP, \fBExternalSensor< DallasTemperature >\fP, and \fBExternalSensor< NDIR_I2C >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBaseExternalSensor\fP ()"
.br
.ti -1c
.RI "virtual uint8_t \fBbegin\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP ()"
.br
.ti -1c
.RI "virtual float \fBread\fP (int16_t *a, int16_t *b, int16_t *c, int16_t *d, int16_t *e, int16_t *f)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is a generic external Sensor it is a way to access real external sensor methods through run Time polymorphism\&. 
.PP
Definition at line 52 of file ExternalSensor\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BaseExternalSensor::BaseExternalSensor ()\fC [inline]\fP"
\fBBaseExternalSensor()\fP: Base class generic Constructor 
.PP
Definition at line 60 of file ExternalSensor\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual uint8_t BaseExternalSensor::begin ()\fC [inline]\fP, \fC [virtual]\fP"
\fBbegin()\fP: Base class virtual generic begin method
.PP
\fBReturns:\fP
.RS 4
generic value as it's not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< Adafruit_ADS1115 >\fP, \fBExternalSensor< Adafruit_ADS1015 >\fP, \fBExternalSensor< Adafruit_TCS34725 >\fP, \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 80 of file ExternalSensor\&.h\&.
.SS "virtual float BaseExternalSensor::read ()\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< DallasTemperature >\fP, \fBExternalSensor< NDIR_I2C >\fP, and \fBExternalSensor< T >\fP\&.
.PP
Definition at line 102 of file ExternalSensor\&.h\&.
.SS "virtual float BaseExternalSensor::read (int16_t * a, int16_t * b, int16_t * c, int16_t * d, int16_t * e, int16_t * f)\fC [inline]\fP, \fC [virtual]\fP"
\fBread()\fP: Base class virtual generic read method
.PP
\fBReturns:\fP
.RS 4
generic value as it is not supposed to be used 
.RE
.PP

.PP
Reimplemented in \fBExternalSensor< Adafruit_ADS1115 >\fP, \fBExternalSensor< Adafruit_ADS1015 >\fP, and \fBExternalSensor< Adafruit_TCS34725 >\fP\&.
.PP
Definition at line 123 of file ExternalSensor\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
