.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolSparkFunBME280.cpp" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolSparkFunBME280.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolSparkFunBME280\&.h'\fP
.br
\fC#include 'stdint\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'Wire\&.h'\fP
.br
\fC#include 'SPI\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
