.TH "CoolBoardSensors::lightActive" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardSensors::lightActive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBvisible\fP =0"
.br
.ti -1c
.RI "bool \fBir\fP =0"
.br
.ti -1c
.RI "bool \fBuv\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBlightActive\fP structure
.PP
set visible to 1 to have visibleLight Readings
.PP
set ir to 1 to have infraRed Readings
.PP
set uv to 1 to have ultraViolet Readings 
.PP
Definition at line 106 of file CoolBoardSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoolBoardSensors::lightActive::ir =0"

.PP
Definition at line 109 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::lightActive::uv =0"

.PP
Definition at line 110 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::lightActive::visible =0"

.PP
Definition at line 108 of file CoolBoardSensors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
