.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolSI114X.cpp" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolSI114X.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolSI114X\&.h'\fP
.br
\fC#include 'Wire\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
