.TH "CoolBoardSensors::airActive" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoolBoardSensors::airActive
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtemperature\fP =0"
.br
.ti -1c
.RI "bool \fBhumidity\fP =0"
.br
.ti -1c
.RI "bool \fBpressure\fP =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBairActive\fP structure
.PP
set temperature to 1 to have temperature Readings
.PP
set humidity to 1 to have humidity Readings
.PP
set pressure to 1 to have pressure Readings 
.PP
Definition at line 123 of file CoolBoardSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool CoolBoardSensors::airActive::humidity =0"

.PP
Definition at line 126 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::airActive::pressure =0"

.PP
Definition at line 127 of file CoolBoardSensors\&.h\&.
.SS "bool CoolBoardSensors::airActive::temperature =0"

.PP
Definition at line 125 of file CoolBoardSensors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
