.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolAdafruit_TCS34725.cpp" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolAdafruit_TCS34725.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Wire\&.h>\fP
.br
\fC#include 'CoolAdafruit_TCS34725\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "float \fBpowf\fP (const float x, const float y)"
.br
.RI "Implements missing powf function\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "float powf (const float x, const float y)"

.PP
Implements missing powf function\&. 
.PP
Definition at line 45 of file CoolAdafruit_TCS34725\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
