.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolNDIR_I2C.h" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolNDIR_I2C.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNDIR_I2C\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
