.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolPubSubClient.cpp" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/CoolPubSubClient.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CoolPubSubClient\&.h'\fP
.br
\fC#include 'Arduino\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMQTT_HEADER_VERSION_LENGTH\fP   7"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MQTT_HEADER_VERSION_LENGTH   7"

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
