.TH "ExternalSensors::sensor" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExternalSensors::sensor
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "String \fBreference\fP =''"
.br
.ti -1c
.RI "String \fBtype\fP =''"
.br
.ti -1c
.RI "uint8_t \fBaddress\fP =0"
.br
.ti -1c
.RI "\fBBaseExternalSensor\fP * \fBexSensor\fP =NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array of 50 External Sensors
.PP
An External Sensor is described by :
.PP
\fBsensor\&.reference\fP : the sensor's reference ( \fBNDIR_I2C\fP\&.\&.\&.)
.PP
\fBsensor\&.type\fP : the sensor's Type ( CO2 , Temperature , \&.\&.\&.\&. )
.PP
\fBsensor\&.address\fP : the sensor's Address if it has one
.PP
\fBsensor\&.exSensor\fP : pointer to the dynmacially instanciated sensor 
.PP
Definition at line 76 of file ExternalSensors\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t ExternalSensors::sensor::address =0"

.PP
Definition at line 80 of file ExternalSensors\&.h\&.
.SS "\fBBaseExternalSensor\fP* ExternalSensors::sensor::exSensor =NULL"

.PP
Definition at line 81 of file ExternalSensors\&.h\&.
.SS "String ExternalSensors::sensor::reference =''"

.PP
Definition at line 78 of file ExternalSensors\&.h\&.
.SS "String ExternalSensors::sensor::type =''"

.PP
Definition at line 79 of file ExternalSensors\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
