.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/irene3000.cpp" 3 "Wed Aug 30 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/irene3000.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include <Arduino\&.h>\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Irene3000\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEBUG   0"

.PP
Definition at line 44 of file irene3000\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
