.TH "Irene3000::parameters_T" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Irene3000::parameters_T
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBWriteCheck\fP =0"
.br
.ti -1c
.RI "int \fBpH7Cal\fP"
.br
.ti -1c
.RI "int \fBpH4Cal\fP =0"
.br
.ti -1c
.RI "float \fBpHStep\fP =1"
.br
.in -1c
.SH "Detailed Description"
.PP 
PH Sensor Calibration parameters
.PP
pH7Cal : PH 7 Calibration value
.PP
pH4Cal : PH 4 Calibration value
.PP
pHStep : PH Slope Step value 
.PP
Definition at line 111 of file Irene3000\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Irene3000::parameters_T::pH4Cal =0"

.PP
Definition at line 114 of file Irene3000\&.h\&.
.SS "int Irene3000::parameters_T::pH7Cal"

.PP
Definition at line 114 of file Irene3000\&.h\&.
.SS "float Irene3000::parameters_T::pHStep =1"

.PP
Definition at line 115 of file Irene3000\&.h\&.
.SS "unsigned int Irene3000::parameters_T::WriteCheck =0"

.PP
Definition at line 113 of file Irene3000\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
