.TH "SensorSettings" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorSettings
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolSparkFunBME280\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBcommInterface\fP"
.br
.ti -1c
.RI "uint8_t \fBI2CAddress\fP"
.br
.ti -1c
.RI "uint8_t \fBchipSelectPin\fP"
.br
.ti -1c
.RI "uint8_t \fBrunMode\fP"
.br
.ti -1c
.RI "uint8_t \fBtStandby\fP"
.br
.ti -1c
.RI "uint8_t \fBfilter\fP"
.br
.ti -1c
.RI "uint8_t \fBtempOverSample\fP"
.br
.ti -1c
.RI "uint8_t \fBpressOverSample\fP"
.br
.ti -1c
.RI "uint8_t \fBhumidOverSample\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file CoolSparkFunBME280\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t SensorSettings::chipSelectPin"

.PP
Definition at line 102 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::commInterface"

.PP
Definition at line 100 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::filter"

.PP
Definition at line 106 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::humidOverSample"

.PP
Definition at line 109 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::I2CAddress"

.PP
Definition at line 101 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::pressOverSample"

.PP
Definition at line 108 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::runMode"

.PP
Definition at line 104 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::tempOverSample"

.PP
Definition at line 107 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorSettings::tStandby"

.PP
Definition at line 105 of file CoolSparkFunBME280\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
