.TH "SensorCalibration" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SensorCalibration
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CoolSparkFunBME280\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBdig_T1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_T2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_T3\fP"
.br
.ti -1c
.RI "uint16_t \fBdig_P1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P2\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P3\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P4\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P5\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P6\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P7\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P8\fP"
.br
.ti -1c
.RI "int16_t \fBdig_P9\fP"
.br
.ti -1c
.RI "uint8_t \fBdig_H1\fP"
.br
.ti -1c
.RI "int16_t \fBdig_H2\fP"
.br
.ti -1c
.RI "uint8_t \fBdig_H3\fP"
.br
.ti -1c
.RI "int16_t \fBdig_H4\fP"
.br
.ti -1c
.RI "int16_t \fBdig_H5\fP"
.br
.ti -1c
.RI "uint8_t \fBdig_H6\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 115 of file CoolSparkFunBME280\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t SensorCalibration::dig_H1"

.PP
Definition at line 132 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_H2"

.PP
Definition at line 133 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorCalibration::dig_H3"

.PP
Definition at line 134 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_H4"

.PP
Definition at line 135 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_H5"

.PP
Definition at line 136 of file CoolSparkFunBME280\&.h\&.
.SS "uint8_t SensorCalibration::dig_H6"

.PP
Definition at line 137 of file CoolSparkFunBME280\&.h\&.
.SS "uint16_t SensorCalibration::dig_P1"

.PP
Definition at line 122 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P2"

.PP
Definition at line 123 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P3"

.PP
Definition at line 124 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P4"

.PP
Definition at line 125 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P5"

.PP
Definition at line 126 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P6"

.PP
Definition at line 127 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P7"

.PP
Definition at line 128 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P8"

.PP
Definition at line 129 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_P9"

.PP
Definition at line 130 of file CoolSparkFunBME280\&.h\&.
.SS "uint16_t SensorCalibration::dig_T1"

.PP
Definition at line 118 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_T2"

.PP
Definition at line 119 of file CoolSparkFunBME280\&.h\&.
.SS "int16_t SensorCalibration::dig_T3"

.PP
Definition at line 120 of file CoolSparkFunBME280\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
