.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/extras/template.h" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/extras/template.h
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const char HTTP_HEAD [] \fBPROGMEM\fP = '<!DOCTYPE html><html lang=\\'en\\'><head><meta name=\\'viewport\\'content=\\'width=device\-width,initial\-scale=1,user\-scalable=no\\'/><title>{v}</title>'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char HTTP_END [] PROGMEM = '<!DOCTYPE html><html lang=\\'en\\'><head><meta name=\\'viewport\\'content=\\'width=device\-width,initial\-scale=1,user\-scalable=no\\'/><title>{v}</title>'"

.PP
Definition at line 1 of file template\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
