.TH "/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/WiFiManagerReadFileButton.cpp" 3 "Tue Sep 19 2017" "CoolBoardAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/ashiroji/Arduino/libraries/CoolBoard/src/internals/WiFiManagerReadFileButton.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'FS\&.h'\fP
.br
\fC#include 'WiFiManagerReadFileButton\&.h'\fP
.br
\fC#include 'ArduinoJson\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CoolBoardAPI from the source code\&.
