CoolBoard API: Adafruit_TCS34725 Class Reference
Adafruit_TCS34725 Class Reference
#include <CoolAdafruit_TCS34725.h>
Public Member Functions
Adafruit_TCS34725 (tcs34725IntegrationTime_t=TCS34725_INTEGRATIONTIME_2_4MS, tcs34725Gain_t=TCS34725_GAIN_1X)
boolean begin (void)
void setIntegrationTime (tcs34725IntegrationTime_t it)
void setGain (tcs34725Gain_t gain)
void getRawData (uint16_t *r, uint16_t *g, uint16_t *b, uint16_t *c)
Reads the raw red, green, blue and clear channel values.
uint16_t calculateColorTemperature (uint16_t r, uint16_t g, uint16_t b)
Converts the raw R/G/B values to color temperature in degrees Kelvin.
uint16_t calculateLux (uint16_t r, uint16_t g, uint16_t b)
Converts the raw R/G/B values to color temperature in degrees Kelvin.
void write8 (uint8_t reg, uint32_t value)
Writes a register and an 8 bit value over I2C.
uint8_t read8 (uint8_t reg)
Reads an 8 bit value over I2C.
uint16_t read16 (uint8_t reg)
Reads a 16 bit values over I2C.
void setInterrupt (boolean flag)
void clearInterrupt (void)
void setIntLimits (uint16_t l, uint16_t h)
void enable (void)
Private Member Functions
void disable (void)
Private Attributes
boolean _tcs34725Initialised
tcs34725Gain_t _tcs34725Gain
tcs34725IntegrationTime_t _tcs34725IntegrationTime
Detailed Description
Definition at line 118 of file CoolAdafruit_TCS34725.h.
Constructor & Destructor Documentation
Adafruit_TCS34725()
Adafruit_TCS34725::Adafruit_TCS34725 (tcs34725IntegrationTime_t it = TCS34725_INTEGRATIONTIME_2_4MS, tcs34725Gain_t gain = TCS34725_GAIN_1X)
Constructor
Definition at line 155 of file CoolAdafruit_TCS34725.cpp.
References _tcs34725Gain, _tcs34725Initialised, and _tcs34725IntegrationTime.
Member Function Documentation
begin()
boolean Adafruit_TCS34725::begin (void)
Initializes I2C and configures the sensor (call this function before doing anything else)
Definition at line 172 of file CoolAdafruit_TCS34725.cpp.
References _tcs34725Gain, _tcs34725Initialised, _tcs34725IntegrationTime, enable(), read8(), setGain(), setIntegrationTime(), and TCS34725_ID.
Referenced by getRawData(), setGain(), and setIntegrationTime().
setIntegrationTime()
void Adafruit_TCS34725::setIntegrationTime (tcs34725IntegrationTime_t it)
Sets the integration time for the TC34725
Definition at line 200 of file CoolAdafruit_TCS34725.cpp.
References _tcs34725Initialised, _tcs34725IntegrationTime, begin(), TCS34725_ATIME, and write8().
Referenced by begin().
setGain()
void Adafruit_TCS34725::setGain (tcs34725Gain_t gain)
Adjusts the gain on the TCS34725 (adjusts the sensitivity to light)
Definition at line 216 of file CoolAdafruit_TCS34725.cpp.
References _tcs34725Gain, _tcs34725Initialised, begin(), TCS34725_CONTROL, and write8().
Referenced by begin().
getRawData()
void Adafruit_TCS34725::getRawData (uint16_t * r, uint16_t * g, uint16_t * b, uint16_t * c)
Reads the raw red, green, blue and clear channel values.
Definition at line 232 of file CoolAdafruit_TCS34725.cpp.
References _tcs34725Initialised, _tcs34725IntegrationTime, begin(), read16(), TCS34725_BDATAL, TCS34725_CDATAL, TCS34725_GDATAL, TCS34725_INTEGRATIONTIME_101MS, TCS34725_INTEGRATIONTIME_154MS, TCS34725_INTEGRATIONTIME_24MS, TCS34725_INTEGRATIONTIME_2_4MS, TCS34725_INTEGRATIONTIME_50MS, TCS34725_INTEGRATIONTIME_700MS, and TCS34725_RDATAL.
calculateColorTemperature()
uint16_t Adafruit_TCS34725::calculateColorTemperature (uint16_t r, uint16_t g, uint16_t b)
Converts the raw R/G/B values to color temperature in degrees Kelvin.
Definition at line 271 of file CoolAdafruit_TCS34725.cpp.
References powf().
calculateLux()
uint16_t Adafruit_TCS34725::calculateLux (uint16_t r, uint16_t g, uint16_t b)
Converts the raw R/G/B values to color temperature in degrees Kelvin.
Definition at line 306 of file CoolAdafruit_TCS34725.cpp.
write8()
void Adafruit_TCS34725::write8 (uint8_t reg, uint32_t value)
Writes a register and an 8 bit value over I2C.
Definition at line 55 of file CoolAdafruit_TCS34725.cpp.
References TCS34725_ADDRESS, and TCS34725_COMMAND_BIT.
Referenced by disable(), enable(), setGain(), setIntegrationTime(), setInterrupt(), and setIntLimits().
read8()
uint8_t Adafruit_TCS34725::read8 (uint8_t reg)
Reads an 8 bit value over I2C.
Definition at line 73 of file CoolAdafruit_TCS34725.cpp.
References TCS34725_ADDRESS, and TCS34725_COMMAND_BIT.
Referenced by begin(), disable(), and setInterrupt().
read16()
uint16_t Adafruit_TCS34725::read16 (uint8_t reg)
Reads a 16 bit values over I2C.
Definition at line 96 of file CoolAdafruit_TCS34725.cpp.
References TCS34725_ADDRESS, and TCS34725_COMMAND_BIT.
Referenced by getRawData().
setInterrupt()
void Adafruit_TCS34725::setInterrupt (boolean flag)
Definition at line 318 of file CoolAdafruit_TCS34725.cpp.
References read8(), TCS34725_ENABLE, TCS34725_ENABLE_AIEN, and write8().
clearInterrupt()
void Adafruit_TCS34725::clearInterrupt (void)
Definition at line 328 of file CoolAdafruit_TCS34725.cpp.
References TCS34725_ADDRESS.
setIntLimits()
void Adafruit_TCS34725::setIntLimits (uint16_t l, uint16_t h)
Definition at line 339 of file CoolAdafruit_TCS34725.cpp.
References write8().
enable()
void Adafruit_TCS34725::enable (void)
Enables the device
Definition at line 126 of file CoolAdafruit_TCS34725.cpp.
References TCS34725_ENABLE, TCS34725_ENABLE_AEN, TCS34725_ENABLE_PON, and write8().
Referenced by begin().
disable()
void Adafruit_TCS34725::disable (void) private
Disables the device (putting it in lower power sleep mode)
Definition at line 138 of file CoolAdafruit_TCS34725.cpp.
References read8(), TCS34725_ENABLE, TCS34725_ENABLE_AEN, TCS34725_ENABLE_PON, and write8().
Member Data Documentation
_tcs34725Initialised
boolean Adafruit_TCS34725::_tcs34725Initialised private
Definition at line 137 of file CoolAdafruit_TCS34725.h.
Referenced by Adafruit_TCS34725(), begin(), getRawData(), setGain(), and setIntegrationTime().
_tcs34725Gain
tcs34725Gain_t Adafruit_TCS34725::_tcs34725Gain private
Definition at line 138 of file CoolAdafruit_TCS34725.h.
Referenced by Adafruit_TCS34725(), begin(), and setGain().
_tcs34725IntegrationTime
tcs34725IntegrationTime_t Adafruit_TCS34725::_tcs34725IntegrationTime private
Definition at line 139 of file CoolAdafruit_TCS34725.h.
Referenced by Adafruit_TCS34725(), begin(), getRawData(), and setIntegrationTime().
The documentation for this class was generated from the following files:
CoolAdafruit_TCS34725.h
CoolAdafruit_TCS34725.cpp