CoolBoard API: ExternalSensors Class Reference
ExternalSensors Class Reference
This class handles the external sensors run time defintion , configuartion and actions.
#include <ExternalSensors.h>
Classes
struct sensor
Public Member Functions
void begin ()
String read ()
bool config ()
bool config (String reference[], String type[], uint8_t address[], int sensorsNumber)
void printConf ()
Private Attributes
struct ExternalSensors::sensor sensors [50]
int sensorsNumber =0
Detailed Description
This class handles the external sensors run time defintion , configuartion and actions.
Definition at line 47 of file ExternalSensors.h.
Class Documentation
ExternalSensors::sensor
struct ExternalSensors::sensor
Array of 50 External Sensors
An External Sensor is described by :
sensor.reference : the sensor's reference (NDIR_I2C...)
sensor.type : the sensor's Type (CO2 , Temperature , ....)
sensor.address : the sensor's Address if it has one
sensor.exSensor : pointer to the dynmacially instanciated sensor
Definition at line 76 of file ExternalSensors.h.
Class Members
String reference
String type
uint8_t address
BaseExternalSensor * exSensor
Member Function Documentation
begin()
void ExternalSensors::begin (void)
ExternalSensors::begin(): This method is provided to initialise the external sensors.
Definition at line 56 of file ExternalSensors.cpp.
References BaseExternalSensor::begin(), ExternalSensors::sensor::exSensor, oneWire(), BaseExternalSensor::read(), sensors, and sensorsNumber.
Referenced by CoolBoard::begin().
read()
String ExternalSensors::read (void)
ExternalSensors::read(): This method is provided to read the data from the external sensors
Returns
json string that contains the sensors data
Definition at line 133 of file ExternalSensors.cpp.
References ExternalSensors::sensor::exSensor, BaseExternalSensor::read(), sensors, sensorsNumber, and ExternalSensors::sensor::type.
Referenced by CoolBoard::readSensors().
config() [1/2]
bool ExternalSensors::config ()
ExternalSensors::config(): This method is provided to configure the externalSensors through a configuration file
Returns
true if successful,false otherwise
Definition at line 237 of file ExternalSensors.cpp.
References ExternalSensors::sensor::address, ExternalSensors::sensor::reference, sensors, sensorsNumber, and ExternalSensors::sensor::type.
Referenced by CoolBoard::begin().
config() [2/2]
bool ExternalSensors::config (String reference[], String type[], uint8_t address[], int sensorsNumber)
ExternalSensors::config(String reference[],String type[],uint8_t address[],int sensorsNumber): This method is provided to configure the externalSensors without a configuration file
Returns
true if successful,false otherwise
Definition at line 402 of file ExternalSensors.cpp.
References ExternalSensors::sensor::address, ExternalSensors::sensor::reference, sensors, sensorsNumber, and ExternalSensors::sensor::type.
printConf()
void ExternalSensors::printConf ()
ExternalSensors::printConf(): This method is provided to print the configuration to the Serial Monitor
Definition at line 445 of file ExternalSensors.cpp.
References sensors, and sensorsNumber.
Referenced by CoolBoard::begin().
Member Data Documentation
sensors
struct ExternalSensors::sensor ExternalSensors::sensors[50] private
Referenced by begin(), config(), printConf(), and read().
sensorsNumber
int ExternalSensors::sensorsNumber =0 private
External Sensors Number Maximum is 50
Definition at line 88 of file ExternalSensors.h.
Referenced by begin(), config(), printConf(), and read().
The documentation for this class was generated from the following files:
ExternalSensors.h
ExternalSensors.cpp