CoolBoard API: CoolBoardLed Class Reference
CoolBoardLed Class Reference
This class handles the led in the Sensor Board.
#include <CoolBoardLed.h>
Public Member Functions
void begin ()
void write (int R, int G, int B)
void end ()
bool config ()
void activate ()
void printConf ()
void fade (int R, int G, int B, float T)
void blink (int R, int G, int B, float T)
void fadeIn (int R, int G, int B, float T)
void fadeOut (int R, int G, int B, float T)
void strobe (int R, int G, int B, float T)
Private Attributes
NeoPixelBus< NeoGrbFeature, Neo800KbpsMethod > * neoPixelLed = NULL
bool ledActive =0
Detailed Description
This class handles the led in the Sensor Board.
Definition at line 45 of file CoolBoardLed.h.
Member Function Documentation
begin()
void CoolBoardLed::begin ()
CoolBoardLed::begin(): This method is provided to start the Led Object by setting the correct pin and creating a dynamic neoPixelBus
Definition at line 249 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config().
write()
void CoolBoardLed::write (int R, int G, int B)
CoolBoardLed::write(Red,Green,Blue): This method is provided to set the Color of the Led
Definition at line 275 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), and CoolBoard::connect().
end()
void CoolBoardLed::end ()
CoolBoardLed::end() : this method is provided to delete the dynamically created neoPixelLed
Definition at line 230 of file CoolBoardLed.cpp.
References neoPixelLed.
config()
bool CoolBoardLed::config ()
CoolBoardLed::config(): This method is provided to configure the Led Object : -ledActive=0 : deactivated -ledActive=1 : activated
Returns
true if the configuration done, false otherwise
Definition at line 308 of file CoolBoardLed.cpp.
References ledActive.
Referenced by CoolBoard::config().
activate()
void CoolBoardLed::activate ()
CoolBoardLed::activate(): This method is provided to activate the Led Object without the configuration file
Definition at line 441 of file CoolBoardLed.cpp.
References ledActive.
printConf()
void CoolBoardLed::printConf ()
CoolBoardLed::printConf(): This method is provided to print the Led Object Configuration to the Serial Monitor
Definition at line 417 of file CoolBoardLed.cpp.
References ledActive.
Referenced by CoolBoard::begin().
fade()
void CoolBoardLed::fade (int R, int G, int B, float T)
CoolBoardLed::fade (Red , Green , Blue, Time in seconds): fade animation: Fade In over T(seconds) Fade Out over T(seconds)
Definition at line 50 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::offLineMode(), and CoolBoard::onLineMode().
blink()
void CoolBoardLed::blink (int R, int G, int B, float T)
CoolBoardLed::blink(Red , Green , Blue , Time in seconds): Blink animation: Led On for T seconds Led off
Definition at line 91 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), CoolBoard::config(), CoolBoard::connect(), CoolBoard::offLineMode(), and CoolBoard::onLineMode().
fadeIn()
void CoolBoardLed::fadeIn (int R, int G, int B, float T)
CoolBoardLed::fadeIn(Red , Green , Blue , Time in seconds) Fade In animation: gradual increase over T(seconds)
Definition at line 124 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config(), CoolBoard::offLineMode(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
fadeOut()
void CoolBoardLed::fadeOut (int R, int G, int B, float T)
CoolBoardLed::fadeOut(Red , Green , Blue , Time in seconds) Fade Out animation: gradual decrease over T(seconds)
Definition at line 159 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::begin(), CoolBoard::config(), CoolBoard::offLineMode(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
strobe()
void CoolBoardLed::strobe (int R, int G, int B, float T)
CoolBoardLed::strobe(Red , Green , Blue , Time in seconds) Strobe animation: blinks over T(seconds)
Definition at line 193 of file CoolBoardLed.cpp.
References ledActive, and neoPixelLed.
Referenced by CoolBoard::config(), CoolBoard::onLineMode(), CoolBoard::readSensors(), and CoolBoard::update().
Member Data Documentation
neoPixelLed
NeoPixelBus<NeoGrbFeature, Neo800KbpsMethod>* CoolBoardLed::neoPixelLed = NULL private
NeoPixel Led Instance
Definition at line 83 of file CoolBoardLed.h.
Referenced by begin(), blink(), end(), fade(), fadeIn(), fadeOut(), strobe(), and write().
ledActive
bool CoolBoardLed::ledActive =0 private
ledActive flag set to 1 if you want LED animation
Definition at line 89 of file CoolBoardLed.h.
Referenced by activate(), begin(), blink(), config(), fade(), fadeIn(), fadeOut(), printConf(), strobe(), and write().
The documentation for this class was generated from the following files:
CoolBoardLed.h
CoolBoardLed.cpp